export const medicalSeedsStrains = [
  {
    id: "channel-plus",
    name: "Channel+",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 20,
    cbd: 0.5,
    indicaPct: 50,
    sativaPct: 50,
    floweringWeeks: 7,
    floweringDays: 50,
    yieldIndoor: 600,
    yieldOutdoor: 1000,
    dominantTerpene: "myrcene",
    aroma: "Dulce terroso, bouquet floral maduro y fondo especiado",
    flavors: ["Dulce Terroso", "Bouquet Floral", "Especiado"],
    effects: ["Relajación Profunda", "Bienestar Físico", "Calma"],
    lineage: "Big Bud x Skunk",
    image: "images/strains/channel-plus.webp"
  },
  {
    id: "1024",
    name: "1024",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 23,
    cbd: 0.3,
    indicaPct: 30,
    sativaPct: 70,
    floweringWeeks: 11,
    floweringDays: 77,
    yieldIndoor: 600,
    yieldOutdoor: 800,
    dominantTerpene: "terpinolene",
    aroma: "Incienso puro, especias orientales, almizcle y fruta madura",
    flavors: ["Incienso Puro", "Especias Orientales", "Fruta Madura"],
    effects: ["Euforia Mental", "Creatividad", "Energía Sativa"],
    lineage: "Genética secreta (Selección Híbrida Sativa)",
    image: "images/strains/1024.webp"
  },
  {
    id: "2046",
    name: "2046",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 25,
    cbd: 0.2,
    indicaPct: 0,
    sativaPct: 100,
    floweringWeeks: 14,
    floweringDays: 100,
    yieldIndoor: 500,
    yieldOutdoor: 700,
    dominantTerpene: "pinene",
    aroma: "Haze catedralicio puro, madera de cedro y fondo anisado",
    flavors: ["Haze Catedralicio", "Madera de Cedro", "Anisado"],
    effects: ["Subidón Psicoactivo", "Euforia Eléctrica", "Claridad"],
    lineage: "Neville's Haze x Neville's Haze",
    image: "images/strains/2046.webp"
  },
  {
    id: "y-griega",
    name: "Y Griega",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 27,
    cbd: 0.4,
    indicaPct: 20,
    sativaPct: 80,
    floweringWeeks: 12,
    floweringDays: 85,
    yieldIndoor: 500,
    yieldOutdoor: 600,
    dominantTerpene: "limonene",
    aroma: "Cítrico alimonado muy penetrante, notas florales silvestres",
    flavors: ["Cítrico Alimonado", "Floral Silvestre", "Haze Fresco"],
    effects: ["Potencia Cerebral", "Estimulación Creativa", "Energía"],
    lineage: "Amnesia Haze x Kali Mist",
    image: "images/strains/y-griega.webp"
  },
  {
    id: "no-name",
    name: "No Name",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Índica",
    thc: 20,
    cbd: 0.4,
    indicaPct: 80,
    sativaPct: 20,
    floweringWeeks: 8,
    floweringDays: 60,
    yieldIndoor: 450,
    yieldOutdoor: 600,
    dominantTerpene: "caryophyllene",
    aroma: "Queso curado Skunk, regaliz dulce y fondo kush terroso",
    flavors: ["Queso Curado Skunk", "Regaliz Dulce", "Kush Terroso"],
    effects: ["Relajación Corporal", "Tranquilidad", "Efecto Sedante"],
    lineage: "Cheese x Sensi Star",
    image: "images/strains/no-name.webp"
  },
  {
    id: "malakoff",
    name: "Malakoff",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 20,
    cbd: 0.3,
    indicaPct: 20,
    sativaPct: 80,
    floweringWeeks: 11,
    floweringDays: 77,
    yieldIndoor: 500,
    yieldOutdoor: 800,
    dominantTerpene: "ocimene",
    aroma: "Frutal ácido, fresa ácida con toque terroso cremoso",
    flavors: ["Fresa Ácida", "Frutal Cremoso", "Toque Terroso"],
    effects: ["Energía Cerebral", "Motivación", "Claridad Sativa"],
    lineage: "Strawberry Haze x White Widow",
    image: "images/strains/malakoff.webp"
  },
  {
    id: "sour-diesel-medical",
    name: "Sour Diesel",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 25,
    cbd: 0.3,
    indicaPct: 30,
    sativaPct: 70,
    floweringWeeks: 10,
    floweringDays: 70,
    yieldIndoor: 500,
    yieldOutdoor: 700,
    dominantTerpene: "myrcene",
    aroma: "Combustible diésel puro, cítrico agrio y notas químicas",
    flavors: ["Gasolina Diésel", "Cítrico Agrio", "Químico Penetrante"],
    effects: ["Euforia Energizante", "Enfoque Mental", "Bienestar"],
    lineage: "Diesel x Northern Lights",
    image: "images/strains/sour-diesel-medical.webp"
  },
  {
    id: "prozack",
    name: "Prozack",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Índica",
    thc: 18,
    cbd: 0.5,
    indicaPct: 80,
    sativaPct: 20,
    floweringWeeks: 9,
    floweringDays: 63,
    yieldIndoor: 450,
    yieldOutdoor: 500,
    dominantTerpene: "caryophyllene",
    aroma: "Hachís afgano tradicional, bosque húmedo y tierra mojada",
    flavors: ["Hachís Afgano", "Bosque Húmedo", "Tierra Mojada"],
    effects: ["Sedación Muscular", "Alivio Físico", "Sueño Reparador"],
    lineage: "Lavander x Kush",
    image: "images/strains/prozack.webp"
  },
  {
    id: "devil-fruit",
    name: "Devil Fruit",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Índica",
    thc: 19,
    cbd: 0.4,
    indicaPct: 70,
    sativaPct: 30,
    floweringWeeks: 9,
    floweringDays: 65,
    yieldIndoor: 500,
    yieldOutdoor: 600,
    dominantTerpene: "linalool",
    aroma: "Frutas tropicales dulces, uva madura y toque floral",
    flavors: ["Frutas Tropicales", "Uva Madura", "Floral Dulce"],
    effects: ["Relajación Placentera", "Paz Mental", "Bienestar Dulce"],
    lineage: "Shiskaberry x Great White Shark",
    image: "images/strains/devil-fruit.webp"
  },
  {
    id: "jack-la-mota",
    name: "Jack La Mota",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 20,
    cbd: 0.3,
    indicaPct: 25,
    sativaPct: 75,
    floweringWeeks: 10,
    floweringDays: 70,
    yieldIndoor: 500,
    yieldOutdoor: 800,
    dominantTerpene: "terpinolene",
    aroma: "Pino silvestre, incienso especiado y maderas aromáticas",
    flavors: ["Pino Silvestre", "Incienso Especiado", "Madera Aromática"],
    effects: ["Euforia Activa", "Claridad Creativa", "Energía Mental"],
    lineage: "Northern Lights #5 x Haze x Skunk",
    image: "images/strains/jack-la-mota.webp"
  },
  {
    id: "mendocino-purple-kush",
    name: "Mendocino Purple Kush",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Índica",
    thc: 20,
    cbd: 0.3,
    indicaPct: 60,
    sativaPct: 40,
    floweringWeeks: 9,
    floweringDays: 60,
    yieldIndoor: 450,
    yieldOutdoor: 600,
    dominantTerpene: "myrcene",
    aroma: "Uva silvestre, frutas del bosque y fondo terroso kush",
    flavors: ["Uva Silvestre", "Frutas del Bosque", "Kush Terroso"],
    effects: ["Relajación Pesada", "Sedación Cálida", "Anti-Estrés"],
    lineage: "Mendocino Purple x Bubba Kush",
    image: "images/strains/mendocino-purple-kush.webp"
  },
  {
    id: "white-widow-medical",
    name: "White Widow",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Índica",
    thc: 19,
    cbd: 0.5,
    indicaPct: 60,
    sativaPct: 40,
    floweringWeeks: 8,
    floweringDays: 58,
    yieldIndoor: 450,
    yieldOutdoor: 750,
    dominantTerpene: "myrcene",
    aroma: "Especiado agridulce, pino fresco y madera con resina espesa",
    flavors: ["Pino Fresco", "Especiado Agridulce", "Madera Resinosa"],
    effects: ["Euforia Clásica", "Relax Corporal", "Equilibrio"],
    lineage: "Landrace Brasil x Landrace Sur de la India",
    image: "images/strains/white-widow-medical.webp"
  },
  {
    id: "canadian-kush-2",
    name: "Canadian Kush 2.0",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Índica",
    thc: 21,
    cbd: 0.3,
    indicaPct: 70,
    sativaPct: 30,
    floweringWeeks: 9,
    floweringDays: 63,
    yieldIndoor: 500,
    yieldOutdoor: 800,
    dominantTerpene: "caryophyllene",
    aroma: "Pino terroso, especias picantes y regusto a combustible",
    flavors: ["Pino Terroso", "Pimienta Picante", "Combustible"],
    effects: ["Sedación Profunda", "Alivio Corporal", "Relax Nocturno"],
    lineage: "Canadian Kush x Casey Jones",
    image: "images/strains/canadian-kush-2.webp"
  },
  {
    id: "overdosis",
    name: "Overdosis",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Índica",
    thc: 24,
    cbd: 0.2,
    indicaPct: 75,
    sativaPct: 25,
    floweringWeeks: 9,
    floweringDays: 60,
    yieldIndoor: 500,
    yieldOutdoor: 600,
    dominantTerpene: "limonene",
    aroma: "Cítrico cremoso, tarta de limón dulce y toques mentolados",
    flavors: ["Tarta de Limón", "Cítrico Cremoso", "Menta Suave"],
    effects: ["Potencia Indica", "Relajación Total", "Efecto Sofá"],
    lineage: "Sunset Sherbert x Wedding Cake",
    image: "images/strains/overdosis.webp"
  },
  {
    id: "banana-z",
    name: "Banana Z",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 23,
    cbd: 0.2,
    indicaPct: 60,
    sativaPct: 40,
    floweringWeeks: 9,
    floweringDays: 63,
    yieldIndoor: 450,
    yieldOutdoor: 500,
    dominantTerpene: "myrcene",
    aroma: "Plátano maduro muy dulce, gominola y fondo Skunk",
    flavors: ["Plátano Maduro", "Gominola Dulce", "Skunk Cremoso"],
    effects: ["Euforia Alegre", "Relajación Dulce", "Bienestar"],
    lineage: "Banana Punch x Zkittlez",
    image: "images/strains/banana-z.webp"
  },
  {
    id: "sundae-float",
    name: "Sundae Float",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 25,
    cbd: 0.2,
    indicaPct: 50,
    sativaPct: 50,
    floweringWeeks: 9,
    floweringDays: 63,
    yieldIndoor: 450,
    yieldOutdoor: 550,
    dominantTerpene: "limonene",
    aroma: "Vainilla cremosa, chocolate dulce y frutas de bosque",
    flavors: ["Vainilla Cremosa", "Chocolate Dulce", "Frutas del Bosque"],
    effects: ["Bienestar Sensorial", "Calma Mental", "Relax Corporal"],
    lineage: "Root Beer Float x Sundae Driver",
    image: "images/strains/sundae-float.webp"
  }
];
