// MEDICAL SEEDS CO. - COLECCIÓN OFICIAL (16 VARIEDADES FEMINIZADAS)
const MEDICAL_SEEDS_DATABASE = [
  {
    id: "channel-plus",
    image: "img/channel-plus.webp",
    name: "Channel+",
    aka: "Big Bud x Skunk",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 20, cbd: 0.5,
    yieldIndoor: 600, yieldOutdoor: 1000,
    floweringDays: 50, rating: 4.9, reviewsCount: 540,
    genetics: "Big Bud x Skunk",
    lineage: "Big Bud x Skunk",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: {myrcene:  50,  caryophyllene:  30,  pinene:  20},
    flavors: ["Dulce Terroso", "Bouquet Floral", "Especiado"],
    effects: ["Relajación Profunda", "Bienestar Físico", "Calma"],
    activities: ["relax_sleep", "social", "gaming"],
    description: "El buque insignia histórico de Medical Seeds y múltiple campeona de copas cannábicas. Famosa por su velocidad asombrosa de floración (menos de 50 días), su colosal producción de cogollos duros como piedras y un equilibrio físico-mental relajante y placentero.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #047857 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "1024",
    image: "img/1024.webp",
    name: "1024",
    aka: "Híbrido Sativa secreto",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 23, cbd: 0.3,
    yieldIndoor: 600, yieldOutdoor: 800,
    floweringDays: 77, rating: 4.9, reviewsCount: 490,
    genetics: "Híbrido Sativa secreto",
    lineage: "Híbrido Sativa secreto",
    origin: "España",
    dominantTerpene: "terpinolene",
    terpenes: {terpinolene:  45,  limonene:  30,  myrcene:  25},
    flavors: ["Incienso Puro", "Especias Orientales", "Fruta Madura"],
    effects: ["Euforia Cerebral", "Creatividad Desbordante", "Energía Mental"],
    activities: ["creativity", "nature_walk", "social"],
    description: "Una auténtica joya secreta de la casa Medical Seeds. Combina en perfecto equilibrio matices de incienso de catedral, especias orientales y frutas maduras, regalando un subidón cerebral eufórico de gran altitud.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #D97706 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "2046",
    image: "img/2046.webp",
    name: "2046",
    aka: "Neville's Haze x Neville's Haze",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 25, cbd: 0.2,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringDays: 100, rating: 4.9, reviewsCount: 520,
    genetics: "Neville's Haze x Neville's Haze",
    lineage: "Neville's Haze x Neville's Haze",
    origin: "España",
    dominantTerpene: "pinene",
    terpenes: {pinene:  45,  terpinolene:  35,  myrcene:  20},
    flavors: ["Haze Catedralicio", "Madera de Cedro", "Anisado"],
    effects: ["Psicoactividad Pura", "Extrema Estimulación", "Claridad Eléctrica"],
    activities: ["creativity", "workout", "social"],
    description: "La reina sativa pura más psicodélica y potente de Medical Seeds. Creada a partir de una retrocruza magistral de Neville's Haze, exige paciencia durante sus 100 días de floración para entregar flores con un subidón eléctrico de intensidad máxima.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #059669 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "y-griega",
    image: "img/y-griega.webp",
    name: "Y Griega",
    aka: "Amnesia Haze x Kali Mist",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 27, cbd: 0.4,
    yieldIndoor: 500, yieldOutdoor: 600,
    floweringDays: 85, rating: 5.0, reviewsCount: 680,
    genetics: "Amnesia Haze x Kali Mist",
    lineage: "Amnesia Haze x Kali Mist",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: {limonene:  50,  myrcene:  30,  pinene:  20},
    flavors: ["Cítrico Alimonado", "Floral Silvestre", "Haze Fresco"],
    effects: ["Subidón Energético", "Euforia Radiante", "Claridad Mental"],
    activities: ["social", "creativity", "nature_walk"],
    description: "Un portento genético que rompió récords históricos con analíticas de hasta un 27% de THC. Cruce arrollador entre Amnesia Haze y Kali Mist, famoso por su marcado sabor a limón fresco y una energía chispeante sin pesadez física.",
    visualColor: "linear-gradient(135deg, #EAB308 0%, #CA8A04 100%)",
    bgPattern: "radial-gradient(circle, rgba(234,179,8,0.25) 0%, transparent 70%)"
  },
  {
    id: "no-name",
    image: "img/no-name.webp",
    name: "No Name",
    aka: "Cheese x Sensi Star",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 20, cbd: 0.4,
    yieldIndoor: 450, yieldOutdoor: 600,
    floweringDays: 60, rating: 4.8, reviewsCount: 430,
    genetics: "Cheese x Sensi Star",
    lineage: "Cheese x Sensi Star",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: {caryophyllene:  45,  myrcene:  35,  humulene:  20},
    flavors: ["Queso Curado Skunk", "Regaliz Dulce", "Fondo Kush Terroso"],
    effects: ["Relajación Fisiológica", "Bienestar Somático", "Paz Mental"],
    activities: ["relax_sleep", "gaming", "meditation"],
    description: "Una de las índicas más premiadas y apreciadas de Medical Seeds. Combina el penetrante olor a queso añejo de la legendaria Cheese británica con la tremenda densidad resinosa y efecto narcótico de Sensi Star.",
    visualColor: "linear-gradient(135deg, #8B5CF6 0%, #6D28D9 100%)",
    bgPattern: "radial-gradient(circle, rgba(139,92,246,0.25) 0%, transparent 70%)"
  },
  {
    id: "malakoff",
    image: "img/malakoff-hd.webp",
    name: "Malakoff",
    aka: "Strawberry Haze x White Widow",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 20, cbd: 0.3,
    indicaPct: 20, sativaPct: 80,
    floweringWeeks: 11, floweringDays: 77,
    yieldIndoor: 500, yieldOutdoor: 800,
    rating: 4.8, reviewsCount: 390,
    genetics: "Strawberry Haze x White Widow",
    lineage: "Strawberry Haze x White Widow",
    origin: "España",
    dominantTerpene: "ocimene",
    terpenes: { ocimene: 40, myrcene: 35, caryophyllene: 25 },
    aroma: "Frutal ácido, fresa ácida con toque terroso cremoso",
    flavors: ["Fresa Ácida", "Fruta Madura", "Terroso Cremoso"],
    effects: ["Energía Positiva", "Risas y Socialización", "Motivación"],
    activities: ["social", "creativity", "nature_walk"],
    description: "Sativa vigorosa y muy resistente a hongos producida cruzando Strawberry Haze con White Widow. Cautiva por su inconfundible sabor a fresas ácidas silvestres sobre un fondo de resina densa y cremosa.",
    visualColor: "linear-gradient(135deg, #EC4899 0%, #BE185D 100%)",
    bgPattern: "radial-gradient(circle, rgba(236,72,153,0.25) 0%, transparent 70%)"
  },
  {
    id: "sour-diesel-medical",
    image: "img/sour-diesel-medical.webp",
    name: "Sour Diesel",
    aka: "Diesel x Northern Lights",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 25, cbd: 0.3,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringDays: 70, rating: 4.9, reviewsCount: 560,
    genetics: "Diesel x Northern Lights",
    lineage: "Diesel x Northern Lights",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: {myrcene:  45,  limonene:  35,  caryophyllene:  20},
    flavors: ["Combustible Diésel", "Cítrico Agrio", "Notas Químicas"],
    effects: ["Euforia Potente", "Claridad Activa", "Despertar Mental"],
    activities: ["gaming", "social", "creativity"],
    description: "La interpretación magistral de Medical Seeds del linaje Sour Diesel, cruzada con Northern Lights para compactar cogollos y maximizar producción sin perder ese aroma inconfundible a hidrocarburo y limón ácido.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #047857 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "prozack",
    image: "img/prozack.webp",
    name: "Prozack",
    aka: "Lavander x Kush",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 18, cbd: 0.5,
    yieldIndoor: 450, yieldOutdoor: 500,
    floweringDays: 63, rating: 4.8, reviewsCount: 410,
    genetics: "Lavander x Kush",
    lineage: "Lavander x Kush",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: {caryophyllene:  45,  myrcene:  35,  humulene:  20},
    flavors: ["Hachís Afgano", "Bosque Húmedo", "Tierra Mojada"],
    effects: ["Relajación Profunda", "Sedación Placentera", "Paz Total"],
    activities: ["relax_sleep", "meditation"],
    description: "Planta de porte achaparrado y cogollos durísimos como rocas procedentes de Lavander x Kush. Destaca por su alta producción de resina de perfil afgano tradicional y su efecto relajante corporal idóneo para combatir el estrés.",
    visualColor: "linear-gradient(135deg, #6366F1 0%, #4338CA 100%)",
    bgPattern: "radial-gradient(circle, rgba(99,102,241,0.25) 0%, transparent 70%)"
  },
  {
    id: "devil-fruit",
    image: "img/devil-fruit.webp",
    name: "Devil Fruit",
    aka: "Shiskaberry x Great White Shark",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 19, cbd: 0.4,
    yieldIndoor: 500, yieldOutdoor: 600,
    floweringDays: 65, rating: 4.8, reviewsCount: 380,
    genetics: "Shiskaberry x Great White Shark",
    lineage: "Shiskaberry x Great White Shark",
    origin: "España",
    dominantTerpene: "linalool",
    terpenes: {linalool:  45,  myrcene:  35,  caryophyllene:  20},
    flavors: ["Frutas Tropicales Dulces", "Uva Madura", "Toque Floral"],
    effects: ["Suavidad Corporal", "Calma Tranquilizadora", "Serenidad"],
    activities: ["relax_sleep", "social", "meditation"],
    description: "Un banquete de frutos del bosque y golosinas tropicales. Gracias a su herencia Shiskaberry x Great White Shark, ofrece una floración repleta de tricomas resplandecientes y una fumada dulce con sedación agradable.",
    visualColor: "linear-gradient(135deg, #F43F5E 0%, #BE123C 100%)",
    bgPattern: "radial-gradient(circle, rgba(244,63,94,0.25) 0%, transparent 70%)"
  },
  {
    id: "jack-la-mota",
    image: "img/jack-la-mota.webp",
    name: "Jack La Mota",
    aka: "Northern Lights #5 x Haze x Skunk",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 20, cbd: 0.3,
    yieldIndoor: 500, yieldOutdoor: 800,
    floweringDays: 70, rating: 4.9, reviewsCount: 510,
    genetics: "Northern Lights #5 x Haze x Skunk",
    lineage: "Northern Lights #5 x Haze x Skunk",
    origin: "España",
    dominantTerpene: "terpinolene",
    terpenes: {terpinolene:  45,  pinene:  30,  myrcene:  25},
    flavors: ["Pino Silvestre", "Incienso Especiado", "Maderas Aromáticas"],
    effects: ["Euforia Activa", "Claridad Inspiradora", "Vitalidad"],
    activities: ["creativity", "gaming", "social"],
    description: "Homenaje de Medical Seeds a Jack Herer, uniendo Northern Lights #5, Haze y Skunk. Cogollos alargados cargados de calices hinchados con fragancia penetrante a pino fresco, incienso litúrgico y madera noble.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #047857 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "mendocino-purple-kush",
    image: "img/mendocino-purple-kush.webp",
    name: "Mendocino Purple Kush",
    aka: "Mendocino Purple x Bubba Kush",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 20, cbd: 0.3,
    yieldIndoor: 450, yieldOutdoor: 600,
    floweringDays: 60, rating: 4.9, reviewsCount: 490,
    genetics: "Mendocino Purple x Bubba Kush",
    lineage: "Mendocino Purple x Bubba Kush",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: {myrcene:  45,  caryophyllene:  30,  pinene:  25},
    flavors: ["Uva Silvestre", "Frutas del Bosque", "Fondo Terroso Kush"],
    effects: ["Relajación Físiológica Profunda", "Bienestar Plácido", "Antiestrés"],
    activities: ["relax_sleep", "gaming", "meditation"],
    description: "La icónica variedad púrpura californiana cruzada magistralmente con Bubba Kush. Despliega hojas y flores de tonalidades violetas fascinantes con un perfume embriagador a uva dulce, tierra húmeda y café tostado.",
    visualColor: "linear-gradient(135deg, #7C3AED 0%, #4C1D95 100%)",
    bgPattern: "radial-gradient(circle, rgba(124,58,237,0.25) 0%, transparent 70%)"
  },
  {
    id: "white-widow-medical",
    image: "img/white-widow-medical.webp",
    name: "White Widow",
    aka: "Brasil x Sur de la India",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 19, cbd: 0.5,
    yieldIndoor: 450, yieldOutdoor: 750,
    floweringDays: 58, rating: 4.8, reviewsCount: 440,
    genetics: "Brasil x Sur de la India",
    lineage: "Brasil x Sur de la India",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: {myrcene:  45,  caryophyllene:  30,  pinene:  25},
    flavors: ["Especiado Agridulce", "Pino Fresco", "Madera y Resina Espesa"],
    effects: ["Golpe Físico Pesado", "Relajación Corporal", "Tranquilidad"],
    activities: ["relax_sleep", "meditation"],
    description: "Selección de la mítica White Widow original de los años 90 (sátiva brasileña x índica del sur de la India). Destaca por su blanca capa nevada de tricomas gruesos y un efecto medicinal contundente.",
    visualColor: "linear-gradient(135deg, #64748B 0%, #334155 100%)",
    bgPattern: "radial-gradient(circle, rgba(100,116,139,0.25) 0%, transparent 70%)"
  },
  {
    id: "canadian-kush-2",
    image: "img/canadian-kush-2.webp",
    name: "Canadian Kush 2.0",
    aka: "Canadian Kush x Casey Jones",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 21, cbd: 0.3,
    yieldIndoor: 500, yieldOutdoor: 800,
    floweringDays: 63, rating: 4.8, reviewsCount: 370,
    genetics: "Canadian Kush x Casey Jones",
    lineage: "Canadian Kush x Casey Jones",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: {caryophyllene:  45,  myrcene:  35,  humulene:  20},
    flavors: ["Pino Terroso", "Especias Picantes", "Regusto a Combustible"],
    effects: ["Inmovilización Corporal", "Alivio Físico Intenso", "Relajo Total"],
    activities: ["relax_sleep", "gaming"],
    description: "Evolución superior de la Canadian Kush original cruzada con el clon Casey Jones. Mayor ramificación, producción generosa de cogollos densos y un aroma penetrante terroso con notas de diesel húmedo.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #047857 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "overdosis",
    image: "img/overdosis.webp",
    name: "Overdosis",
    aka: "Sunset Sherbert x Wedding Cake",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 24, cbd: 0.2,
    yieldIndoor: 500, yieldOutdoor: 600,
    floweringDays: 60, rating: 4.9, reviewsCount: 460,
    genetics: "Sunset Sherbert x Wedding Cake",
    lineage: "Sunset Sherbert x Wedding Cake",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: {limonene:  45,  caryophyllene:  35,  myrcene:  20},
    flavors: ["Cítrico Cremoso", "Tarta de Limón Dulce", "Toques Mentolados"],
    effects: ["Euforia Agradable", "Relajación Muscular", "Placer Sensorial"],
    activities: ["social", "gaming", "relax_sleep"],
    description: "Un festín goloso entre Sunset Sherbert y Wedding Cake. Flores de estructura rocosa y colores pastel con un sabor sedoso a tarta de limón horneada, crema dulce y una suave relajación integral.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #D97706 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "banana-z",
    image: "img/banana-z.webp",
    name: "Banana Z",
    aka: "Banana Punch x Zkittlez",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 23, cbd: 0.2,
    yieldIndoor: 450, yieldOutdoor: 500,
    floweringDays: 63, rating: 4.9, reviewsCount: 420,
    genetics: "Banana Punch x Zkittlez",
    lineage: "Banana Punch x Zkittlez",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: {myrcene:  45,  limonene:  35,  caryophyllene:  20},
    flavors: ["Plátano Maduro Dulce", "Gominola Frutal", "Fondo Skunk"],
    effects: ["Felicidad Eufórica", "Paz Sensorial", "Bienestar"],
    activities: ["social", "gaming", "relax_sleep"],
    description: "Explosión de sabor a plátano dulce maduro y gominolas frutales gracias a la combinación de Banana Punch y Zkittlez. Gran cantidad de terpenos aromáticos y efecto equilibrado y alegre.",
    visualColor: "linear-gradient(135deg, #EAB308 0%, #CA8A04 100%)",
    bgPattern: "radial-gradient(circle, rgba(234,179,8,0.25) 0%, transparent 70%)"
  },
  {
    id: "sundae-float",
    image: "img/sundae-float.webp",
    name: "Sundae Float",
    aka: "Root Beer Float x Sundae Driver",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 25, cbd: 0.2,
    yieldIndoor: 450, yieldOutdoor: 550,
    floweringDays: 63, rating: 4.9, reviewsCount: 450,
    genetics: "Root Beer Float x Sundae Driver",
    lineage: "Root Beer Float x Sundae Driver",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: {limonene:  45,  caryophyllene:  35,  linalool:  20},
    flavors: ["Vainilla Cremosa", "Chocolate Dulce", "Frutas de Bosque"],
    effects: ["Euforia Gostosa", "Relajación Corporal", "Tranquilidad Mental"],
    activities: ["gaming", "social", "relax_sleep"],
    description: "Un cóctel cremoso extraordinario que une Root Beer Float con Sundae Driver. Destaca por sus aromas envolventes a vainilla dulce, cacao, matices anisados y un golpe potente y reconfortante.",
    visualColor: "linear-gradient(135deg, #EC4899 0%, #8B5CF6 100%)",
    bgPattern: "radial-gradient(circle, rgba(236,72,153,0.25) 0%, transparent 70%)"
  }
];
