// Medical Seeds Co. - 42 Variedades Feminizadas Oficiales (100% Fotos Reales HD)
export const medicalSeedsStrains = [
  {
    id: "channel-plus",
    image: "img/channel-plus.webp",
    name: "Channel+",
    aka: "Big Bud x Skunk",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 20, cbd: 0.5,
    indicaPct: 50, sativaPct: 50,
    yieldIndoor: 600, yieldOutdoor: 1000,
    floweringWeeks: 7, floweringDays: 50,
    rating: 4.9, reviewsCount: 540,
    genetics: "Big Bud x Skunk",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 50, caryophyllene: 30, pinene: 20 },
    aroma: "Dulce terroso, bouquet floral maduro y fondo especiado",
    flavors: ["Dulce Terroso", "Bouquet Floral", "Especiado"],
    effects: ["Relajación Profunda", "Bienestar Físico", "Calma"],
    activities: ["relax_sleep", "social", "gaming"],
    description: "El buque insignia histórico de Medical Seeds y múltiple campeona de copas cannábicas. Famosa por su velocidad asombrosa de floración (menos de 50 días), su colosal producción de cogollos duros como piedras y un equilibrio físico-mental relajante y placentero.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #047857 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "1024",
    image: "img/1024.webp",
    name: "1024",
    aka: "Selección Híbrida Sativa Secreta",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 23, cbd: 0.3,
    indicaPct: 30, sativaPct: 70,
    yieldIndoor: 600, yieldOutdoor: 800,
    floweringWeeks: 11, floweringDays: 77,
    rating: 4.9, reviewsCount: 490,
    genetics: "Genética secreta (Selección Híbrida Sativa)",
    origin: "España",
    dominantTerpene: "terpinolene",
    terpenes: { terpinolene: 45, limonene: 30, myrcene: 25 },
    aroma: "Incienso puro, especias orientales, almizcle y fruta madura",
    flavors: ["Incienso Puro", "Especias Orientales", "Fruta Madura"],
    effects: ["Euforia Mental", "Creatividad", "Energía Sativa"],
    activities: ["creativity", "social", "nature_walk"],
    description: "Una auténtica joya botánica de efecto eléctrico y sabores catedralicios. Su complejo buqué combina notas a incienso sagrado, madera noble y toques de mango maduro, desatando una oleada de creatividad efervescente inigualable.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #B45309 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "2046",
    image: "img/2046.webp",
    name: "2046",
    aka: "Neville's Haze x Neville's Haze",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 25, cbd: 0.2,
    indicaPct: 0, sativaPct: 100,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 14, floweringDays: 100,
    rating: 4.8, reviewsCount: 380,
    genetics: "Neville's Haze x Neville's Haze",
    origin: "España",
    dominantTerpene: "pinene",
    terpenes: { pinene: 50, terpinolene: 30, caryophyllene: 20 },
    aroma: "Haze catedralicio puro, madera de cedro y fondo anisado",
    flavors: ["Haze Catedralicio", "Madera de Cedro", "Anisado"],
    effects: ["Subidón Psicoactivo", "Euforia Eléctrica", "Claridad"],
    activities: ["creativity", "nature_walk", "workout"],
    description: "Una Sativa pura al 100% no apta para principiantes. Con 14 semanas de paciente floración, regala la experiencia más psicodélica y lúcida del banco, con una explosión terpénica a cedro fresco, pino salvaje e incienso de iglesia antigua.",
    visualColor: "linear-gradient(135deg, #EAB308 0%, #A16207 100%)",
    bgPattern: "radial-gradient(circle, rgba(234,179,8,0.25) 0%, transparent 70%)"
  },
  {
    id: "y-griega",
    image: "img/y-griega.webp",
    name: "Y Griega",
    aka: "Amnesia Haze x Kali Mist",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 27, cbd: 0.4,
    indicaPct: 20, sativaPct: 80,
    yieldIndoor: 500, yieldOutdoor: 600,
    floweringWeeks: 12, floweringDays: 85,
    rating: 4.9, reviewsCount: 580,
    genetics: "Amnesia Haze x Kali Mist",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 45, myrcene: 30, pinene: 25 },
    aroma: "Cítrico alimonado muy penetrante, notas florales silvestres",
    flavors: ["Cítrico Alimonado", "Floral Silvestre", "Haze Fresco"],
    effects: ["Potencia Cerebral", "Estimulación Creativa", "Energía"],
    activities: ["creativity", "social", "gaming"],
    description: "Mítica leyenda de Medical Seeds que rompió récords históricos superando el 27% de THC en analíticas de cromatografía. Combina el vigor indomable de Kali Mist con el bouquet cítrico picante de Amnesia Haze en una flor densa y empapada en tricomas gigantescos.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #D97706 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "no-name",
    image: "img/no-name.webp",
    name: "No Name",
    aka: "Cheese x Sensi Star",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 20, cbd: 0.4,
    indicaPct: 80, sativaPct: 20,
    yieldIndoor: 450, yieldOutdoor: 600,
    floweringWeeks: 8, floweringDays: 60,
    rating: 4.8, reviewsCount: 430,
    genetics: "Cheese x Sensi Star",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: { caryophyllene: 45, myrcene: 35, humulene: 20 },
    aroma: "Queso curado penetrante, fondo a Skunk vieja escuela y regaliz",
    flavors: ["Queso Curado", "Skunk Añejo", "Regaliz Negro"],
    effects: ["Relajación Corporal", "Bienestar Somático", "Calma"],
    activities: ["relax_sleep", "meditation"],
    description: "Cruce sublime entre una selección selecta de Cheese y la mítica Sensi Star. Inicia con una estimulación cerebral muy alegre que rápidamente se transforma en un estado de profunda paz física y bienestar somático libre de estrés.",
    visualColor: "linear-gradient(135deg, #8B5CF6 0%, #6D28D9 100%)",
    bgPattern: "radial-gradient(circle, rgba(139,92,246,0.25) 0%, transparent 70%)"
  },
  {
    id: "sour-diesel-medical",
    image: "img/sour-diesel-medical.webp",
    name: "Sour Diesel",
    aka: "Selección Original East Coast Sour Diesel",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 25, cbd: 0.3,
    indicaPct: 30, sativaPct: 70,
    yieldIndoor: 500, yieldOutdoor: 600,
    floweringWeeks: 10, floweringDays: 70,
    rating: 4.9, reviewsCount: 420,
    genetics: "Selección Original Sour Diesel",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 40, caryophyllene: 35, myrcene: 25 },
    aroma: "Combustible diésel puro, cítrico químico y toques terrosos",
    flavors: ["Gasolina Diésel", "Limón Químico", "Tierra Húmeda"],
    effects: ["Euforia Dinámica", "Claridad Mental", "Motivación"],
    activities: ["social", "workout", "creativity"],
    description: "La versión maestra de Medical Seeds de la legendaria East Coast Sour Diesel. Desprende un aroma inconfundible a queroseno y limón ácido que llena cualquier espacio, ofreciendo un efecto energizante perfecto para proyectos artísticos y actividades diurnas.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #D97706 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "prozack",
    image: "img/prozack.webp",
    name: "Prozack",
    aka: "Lavander x Kush",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 18, cbd: 0.8,
    indicaPct: 80, sativaPct: 20,
    yieldIndoor: 450, yieldOutdoor: 500,
    floweringWeeks: 8, floweringDays: 56,
    rating: 4.8, reviewsCount: 360,
    genetics: "Lavander x Kush",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 50, linalool: 30, caryophyllene: 20 },
    aroma: "Hachís dulce de alta montaña, lavanda y tierra húmeda",
    flavors: ["Hachís Dulce", "Lavanda Fresca", "Tierra Profunda"],
    effects: ["Relajación Máxima", "Alivio de Tensión", "Paz Mental"],
    activities: ["relax_sleep", "meditation"],
    description: "Planta compacta de porte arbustivo ideal para extracciones de resina de campeonato. Une los matices florales a lavanda con el vigor terroso del Kush afgano, induciendo un efecto sedante sumamente agradable y terapéutico.",
    visualColor: "linear-gradient(135deg, #8B5CF6 0%, #5B21B6 100%)",
    bgPattern: "radial-gradient(circle, rgba(139,92,246,0.25) 0%, transparent 70%)"
  },
  {
    id: "malakoff",
    image: "img/malakoff.webp",
    name: "Malakoff",
    aka: "Strawberry Haze x White Widow",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 20, cbd: 0.4,
    indicaPct: 20, sativaPct: 80,
    yieldIndoor: 400, yieldOutdoor: 600,
    floweringWeeks: 11, floweringDays: 75,
    rating: 4.8, reviewsCount: 390,
    genetics: "Strawberry Haze x White Widow",
    origin: "España",
    dominantTerpene: "terpinolene",
    terpenes: { terpinolene: 45, limonene: 30, myrcene: 25 },
    aroma: "Fresas ácidas, crema dulce y fondo Haze resinoso",
    flavors: ["Fresa Silvestre", "Crema Dulce", "Haze Especiado"],
    effects: ["Subidón Cerebral", "Buen Humor", "Creatividad"],
    activities: ["creativity", "social", "nature_walk"],
    description: "Una Sativa fresca y sumamente resistente a hongos como el botrytis, perfecta para cultivadores de exterior en climas húmedos. Regala un delicioso sabor a fresas silvestres maduras con un fondo especiado que invita a la socialización y la risa.",
    visualColor: "linear-gradient(135deg, #EC4899 0%, #BE185D 100%)",
    bgPattern: "radial-gradient(circle, rgba(236,72,153,0.25) 0%, transparent 70%)"
  },
  {
    id: "jack-la-mota",
    image: "img/jack-la-mota.webp",
    name: "Jack La Mota",
    aka: "Northern Lights #5 x Haze x Skunk",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 20, cbd: 0.3,
    indicaPct: 25, sativaPct: 75,
    yieldIndoor: 500, yieldOutdoor: 800,
    floweringWeeks: 9, floweringDays: 65,
    rating: 4.9, reviewsCount: 510,
    genetics: "Northern Lights #5 x Haze x Skunk",
    origin: "España",
    dominantTerpene: "terpinolene",
    terpenes: { terpinolene: 40, pinene: 35, caryophyllene: 25 },
    aroma: "Incienso puro, madera de pino y especias picantes",
    flavors: ["Incienso Puro", "Pino Fresco", "Especias"],
    effects: ["Euforia Activa", "Claridad Mental", "Energía Social"],
    activities: ["social", "creativity", "nature_walk"],
    description: "El homenaje definitivo de Medical Seeds a Jack Herer. Produce cálices voluminosos cubiertos de cristales plateados con un perfil organoléptico dominado por el incienso catedralicio y la resina de pino, otorgando una euforia lúcida y energética.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #B45309 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "mendocino-purple-kush",
    image: "img/mendocino-purple-kush.webp",
    name: "Mendocino Purple Kush",
    aka: "Mendocino Purple x Bubba Kush",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 20, cbd: 0.4,
    indicaPct: 60, sativaPct: 40,
    yieldIndoor: 450, yieldOutdoor: 600,
    floweringWeeks: 9, floweringDays: 60,
    rating: 4.9, reviewsCount: 560,
    genetics: "Mendocino Purple x Bubba Kush",
    origin: "España",
    dominantTerpene: "linalool",
    terpenes: { linalool: 45, myrcene: 30, caryophyllene: 25 },
    aroma: "Uva dulce madura, tierra mojada y fondo Kush intenso",
    flavors: ["Uva Dulce", "Tierra Húmeda", "Kush Terroso"],
    effects: ["Relajación Intensa", "Bienestar Físico", "Calma Serena"],
    activities: ["relax_sleep", "meditation"],
    description: "Una de las reinas visuales del catálogo con cuatro fenotipos que van del verde esmeralda al violeta más oscuro y aterciopelado. Su aroma recuerda a racimos de uvas maduras recién cosechadas combinadas con el cuerpo denso y narcótico de Bubba Kush.",
    visualColor: "linear-gradient(135deg, #9333EA 0%, #581C87 100%)",
    bgPattern: "radial-gradient(circle, rgba(147,51,234,0.25) 0%, transparent 70%)"
  },
  {
    id: "devil-fruit",
    image: "img/devil-fruit.webp",
    name: "Devil Fruit",
    aka: "Shiskaberry x Great White Shark",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 18, cbd: 0.5,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 600,
    floweringWeeks: 9, floweringDays: 65,
    rating: 4.8, reviewsCount: 370,
    genetics: "Shiskaberry x Great White Shark",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, limonene: 35, caryophyllene: 20 },
    aroma: "Frutas rojas maduras, bayas silvestres y fondo dulce almibarado",
    flavors: ["Frutas Rojas", "Golosina Dulce", "Fondo Herbal"],
    effects: ["Relajación Corporal", "Paz Mental", "Bienestar Suave"],
    activities: ["relax_sleep", "social"],
    description: "Variedad sumamente dulce y apetecible nacida del cruce entre Shiskaberry y Great White Shark. Su aroma a caramelo de frutos rojos envuelve los sentidos mientras su efecto físico relaja la musculatura sin dejarte clavado al sofá.",
    visualColor: "linear-gradient(135deg, #EC4899 0%, #831843 100%)",
    bgPattern: "radial-gradient(circle, rgba(236,72,153,0.25) 0%, transparent 70%)"
  },
  {
    id: "white-widow-medical",
    image: "img/white-widow-medical.webp",
    name: "White Widow",
    aka: "Selección Original White Widow",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 18, cbd: 0.6,
    indicaPct: 50, sativaPct: 50,
    yieldIndoor: 450, yieldOutdoor: 750,
    floweringWeeks: 9, floweringDays: 60,
    rating: 4.8, reviewsCount: 440,
    genetics: "Selección Original White Widow (Brazilian x South Indian)",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 40, caryophyllene: 35, pinene: 25 },
    aroma: "Pino fresco, especias dulces y fondo floral terroso",
    flavors: ["Pino Fresco", "Especias Dulces", "Terroso Clásico"],
    effects: ["Equilibrio Mental", "Relajación Física", "Serenidad"],
    activities: ["social", "gaming", "relax_sleep"],
    description: "La versión pura de Medical Seeds del clásico holandés que definió los años 90. Destaca por su manto ininterrumpido de tricomas blancos como la nieve, su sabor especiado a bosque otoñal y su balance terapéutico reconfortante.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #065F46 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "canadian-kush",
    image: "img/canadian-kush.webp",
    name: "Canadian Kush",
    aka: "Purple Kush x Special Kush",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 21, cbd: 0.3,
    indicaPct: 100, sativaPct: 0,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 9, floweringDays: 63,
    rating: 4.9, reviewsCount: 460,
    genetics: "Purple Kush x Special Kush",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 50, caryophyllene: 30, pinene: 20 },
    aroma: "Pino húmedo, tierra mojada, uva terrosa y hachís afgano",
    flavors: ["Pino Húmedo", "Tierra Mojada", "Hachís Dulce"],
    effects: ["Narcótico Fuerte", "Relajación Corporal", "Paz Profunda"],
    activities: ["relax_sleep", "meditation"],
    description: "Una índica canadiense 100% pura y devastadora que combina la pigmentación violeta de Purple Kush con la potencia densa de Special Kush. Flores duras como piedras impregnadas en resina aromática a bosque boreal y hachís tradicional.",
    visualColor: "linear-gradient(135deg, #6B21A8 0%, #3B0764 100%)",
    bgPattern: "radial-gradient(circle, rgba(107,33,168,0.25) 0%, transparent 70%)"
  },
  {
    id: "canadian-kush-2",
    image: "img/canadian-kush-2.webp",
    name: "Canadian Kush 2.0",
    aka: "Canadian Kush x Casey Jones",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 22, cbd: 0.2,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 550,
    floweringWeeks: 9, floweringDays: 63,
    rating: 4.8, reviewsCount: 350,
    genetics: "Canadian Kush x Casey Jones",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, caryophyllene: 35, limonene: 20 },
    aroma: "Tierra húmeda, gas diésel suave, pino resinoso y frutos oscuros",
    flavors: ["Tierra Húmeda", "Diésel Suave", "Pino Resinoso"],
    effects: ["Pegada Contundente", "Desconexión Total", "Paz Somática"],
    activities: ["relax_sleep", "gaming"],
    description: "Evolución magistral de la Canadian Kush cruzada con el vigor de Casey Jones. Incrementa la producción y aporta un regusto a carburante noble que complementa a la perfección su carácter terroso y relajante.",
    visualColor: "linear-gradient(135deg, #7C3AED 0%, #4C1D95 100%)",
    bgPattern: "radial-gradient(circle, rgba(124,58,237,0.25) 0%, transparent 70%)"
  },
  {
    id: "banana-z",
    image: "img/banana-z.webp",
    name: "Banana Zkittlez",
    aka: "Banana Punch x Zkittlez",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 23, cbd: 0.2,
    indicaPct: 60, sativaPct: 40,
    yieldIndoor: 450, yieldOutdoor: 500,
    floweringWeeks: 9, floweringDays: 63,
    rating: 4.9, reviewsCount: 480,
    genetics: "Banana Punch x Zkittlez",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, limonene: 35, caryophyllene: 20 },
    aroma: "Plátano maduro muy dulce, gominola y fondo Skunk cremoso",
    flavors: ["Plátano Maduro", "Gominola Dulce", "Skunk Cremoso"],
    effects: ["Euforia Alegre", "Relajación Dulce", "Bienestar"],
    activities: ["social", "gaming", "creativity"],
    description: "Una auténtica fiesta tropical para el paladar. Reúne los terpenos a plátano dulce de Banana Punch con la explosión caramelizada de Zkittlez, brindando un colocón risueño y muy sociable perfecto para desconectar con una sonrisa.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #F59E0B 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "banana-purp",
    image: "img/banana-purp.webp",
    name: "Banana Purp",
    aka: "Banana Punch x Purple Punch",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 24, cbd: 0.2,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 10, floweringDays: 67,
    rating: 4.9, reviewsCount: 410,
    genetics: "Banana Punch x Purple Punch",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, caryophyllene: 30, limonene: 25 },
    aroma: "Plátano maduro dulce, uva silvestre, fondo terroso acaramelado",
    flavors: ["Plátano Maduro", "Uva Silvestre", "Caramelo Dulce"],
    effects: ["Relajación Muscular", "Sedación Placentera", "Paz Mental"],
    activities: ["relax_sleep", "meditation"],
    description: "Híbrido de impactantes tonos morados y aroma a batido de plátano con moras silvestres. Los cálices se hinchan cubriéndose de resina pegajosa que garantiza una sedación física ideal para combatir el insomnio y la fatiga.",
    visualColor: "linear-gradient(135deg, #8B5CF6 0%, #D97706 100%)",
    bgPattern: "radial-gradient(circle, rgba(139,92,246,0.25) 0%, transparent 70%)"
  },
  {
    id: "blue-hell",
    image: "img/blue-hell.webp",
    name: "Blue Hell",
    aka: "DJ Short Blueberry Selección Original",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 21, cbd: 0.3,
    indicaPct: 80, sativaPct: 20,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 10, floweringDays: 67,
    rating: 4.9, reviewsCount: 520,
    genetics: "DJ Short Blueberry (Selección Original)",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 50, caryophyllene: 25, pinene: 25 },
    aroma: "Arándanos frescos silvestres, bayas del bosque y matices florales",
    flavors: ["Arándano Silvestre", "Frutas del Bosque", "Muffin Dulce"],
    effects: ["Narcótico Suave", "Alivio de Dolores", "Descanso Físico"],
    activities: ["relax_sleep", "meditation"],
    description: "Una de las selecciones más prestigiosas del mítico clon original de DJ Short Blueberry de los años 2000. Conserva el bouquet legendario a tarta de arándanos con un humo denso y azulado que reconforta el cuerpo entero.",
    visualColor: "linear-gradient(135deg, #3B82F6 0%, #1D4ED8 100%)",
    bgPattern: "radial-gradient(circle, rgba(59,130,246,0.25) 0%, transparent 70%)"
  },
  {
    id: "bluehell-cbd",
    image: "img/bluehell-cbd.webp",
    name: "Bluehell CBD",
    aka: "Blue Hell x Medical CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 8, cbd: 14,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 9, floweringDays: 60,
    rating: 4.8, reviewsCount: 380,
    genetics: "Blue Hell x Medical CBD",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, pinene: 30, caryophyllene: 25 },
    aroma: "Arándano dulce azul, fruta madura y fondo herbal balsámico",
    flavors: ["Arándano Azul", "Fruta Madura", "Herbal Balsámico"],
    effects: ["Alivio Terapéutico", "Relajación Sin Niebla", "Calma Corporal"],
    activities: ["meditation", "nature_walk", "relax_sleep"],
    description: "La versión médica con ratio 1:2 (THC 8% : CBD 14%) del legendario clon Blue Hell. Mantiene intacto el irresistible perfil de frutos del bosque mientras aporta una profunda relajación somática libre de ansiedad o niebla mental.",
    visualColor: "linear-gradient(135deg, #06B6D4 0%, #0E7490 100%)",
    bgPattern: "radial-gradient(circle, rgba(6,182,212,0.25) 0%, transparent 70%)"
  },
  {
    id: "chocogas",
    image: "img/chocogas.webp",
    name: "ChocoGas",
    aka: "Chocolope x Gas",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 24, cbd: 0.1,
    indicaPct: 80, sativaPct: 20,
    yieldIndoor: 500, yieldOutdoor: 550,
    floweringWeeks: 9, floweringDays: 63,
    rating: 4.8, reviewsCount: 340,
    genetics: "Chocolope x Gas",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: { caryophyllene: 45, myrcene: 35, humulene: 20 },
    aroma: "Chocolate negro profundo, carburante diésel y toques amaderados",
    flavors: ["Chocolate Negro", "Combustible Diésel", "Madera Noble"],
    effects: ["Pegada Contundente", "Bienestar Cálido", "Relax Profundo"],
    activities: ["relax_sleep", "gaming"],
    description: "Una combinación seductora y penetrante que fusiona los tonos a cacao amargo de Chocolope con la agresividad resinosa y química del corte Gas. Potente efecto corporal con un retrogusto persistente a bombón de chocolate negro con queroseno.",
    visualColor: "linear-gradient(135deg, #78350F 0%, #451A03 100%)",
    bgPattern: "radial-gradient(circle, rgba(120,53,15,0.25) 0%, transparent 70%)"
  },
  {
    id: "cookies-purple-punch",
    image: "img/cookies-purple-punch.webp",
    name: "Cookies Purple Punch",
    aka: "Girl Scout Cookies x Purple Punch",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 24, cbd: 0.2,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 10, floweringDays: 70,
    rating: 4.9, reviewsCount: 470,
    genetics: "Girl Scout Cookies x Purple Punch",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: { caryophyllene: 40, limonene: 35, myrcene: 25 },
    aroma: "Galletas recién horneadas, uva madura, caramelo y pastel de frutas",
    flavors: ["Galleta Dulce", "Pastel de Uva", "Vainilla Especiada"],
    effects: ["Placer Sensorial", "Sedación Gradual", "Eufórico Feliz"],
    activities: ["social", "gaming", "relax_sleep"],
    description: "El matrimonio perfecto de dos gigantes de la costa oeste estadounidense. Cogollos densos bañados en azúcar con matices a galleta de mantequilla, vainilla especiada y mosto de uva madura, desatando una dicha placentera instantánea.",
    visualColor: "linear-gradient(135deg, #A855F7 0%, #6B21A8 100%)",
    bgPattern: "radial-gradient(circle, rgba(168,85,247,0.25) 0%, transparent 70%)"
  },
  {
    id: "deep-neville",
    image: "img/deep-neville.webp",
    name: "Deep Neville",
    aka: "Neville's Haze x Deep Chunk",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 22, cbd: 0.3,
    indicaPct: 50, sativaPct: 50,
    yieldIndoor: 500, yieldOutdoor: 550,
    floweringWeeks: 10, floweringDays: 67,
    rating: 4.8, reviewsCount: 390,
    genetics: "Neville's Haze x Deep Chunk",
    origin: "España",
    dominantTerpene: "pinene",
    terpenes: { pinene: 45, myrcene: 35, caryophyllene: 20 },
    aroma: "Incienso metálico Haze, pino húmedo y fondo terroso afgano",
    flavors: ["Incienso Metálico", "Pino Silvestre", "Terroso Afgano"],
    effects: ["Psicoactividad Intensa", "Enfoque Mental", "Cuerpo Anclado"],
    activities: ["creativity", "meditation"],
    description: "Cruce fascinante que doma la legendaria Neville's Haze con la robustez ancestral de la Deep Chunk afgana. Genera flores firmes con un aroma punzante a resina de pino e incienso catedralicio y un subidón cerebral muy concentrado.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #065F46 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "eboshi-cbg",
    image: "img/eboshi-cbg.webp",
    name: "Eboshi CBG",
    aka: "Eboshi CBG Selección Médica",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 0.2, cbd: 0.1,
    indicaPct: 80, sativaPct: 20,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 8, floweringDays: 56,
    rating: 4.9, reviewsCount: 320,
    genetics: "Eboshi CBG Selection (~15% CBG puro)",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, pinene: 35, caryophyllene: 20 },
    aroma: "Cítrico terroso suave, sándalo y notas frescas herbales",
    flavors: ["Cítrico Suave", "Sándalo", "Herbal Fresco"],
    effects: ["Claridad Terapéutica", "Antiinflamatorio", "Relajación Pura"],
    activities: ["meditation", "nature_walk", "workout"],
    description: "Pionera mundial en la investigación de cannabinoides menores. Con un impresionante 15% de CBG (Cannabigerol) y menos de 0.2% de THC, no produce alteración psicoactiva alguna, ofreciendo extraordinarias propiedades antiinflamatorias y neuroprotectoras.",
    visualColor: "linear-gradient(135deg, #06B6D4 0%, #047857 100%)",
    bgPattern: "radial-gradient(circle, rgba(6,182,212,0.25) 0%, transparent 70%)"
  },
  {
    id: "elixir-vitae-cbd",
    image: "img/elixir-vitae-cbd.webp",
    name: "Elixir Vitae CBD",
    aka: "Jean Dark CBD x Medical CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 0.2, cbd: 14,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 8, floweringDays: 57,
    rating: 4.8, reviewsCount: 360,
    genetics: "Jean Dark CBD x Medical CBD (<0.25% THC)",
    origin: "España",
    dominantTerpene: "terpinolene",
    terpenes: { terpinolene: 40, myrcene: 35, pinene: 25 },
    aroma: "Caramelo tostado, corteza de pino, flores silvestres y cítrico suave",
    flavors: ["Caramelo Tostado", "Corteza de Pino", "Floral Silvestre"],
    effects: ["Antiestrés Absoluto", "Alivio Muscular", "Claridad Terapéutica"],
    activities: ["meditation", "relax_sleep", "nature_walk"],
    description: "El auténtico bálsamo medicinal de Medical Seeds con ratio CBD:THC de 70:1 (<0.25% THC). Ideal para usuarios terapéuticos que buscan disolver la ansiedad cotidiana y el dolor articular manteniendo una mente totalmente despejada.",
    visualColor: "linear-gradient(135deg, #0891B2 0%, #0E7490 100%)",
    bgPattern: "radial-gradient(circle, rgba(8,145,178,0.25) 0%, transparent 70%)"
  },
  {
    id: "gelato-242",
    image: "img/gelato-242.webp",
    name: "Gelato 242",
    aka: "Sunset Sherbert x Thin Mint GSC",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 24, cbd: 0.2,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 10, floweringDays: 67,
    rating: 4.9, reviewsCount: 490,
    genetics: "Sunset Sherbert x Thin Mint Girl Scout Cookies",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 45, caryophyllene: 35, myrcene: 20 },
    aroma: "Helado cremoso de naranja dulce, toques mentolados y fondo Kush",
    flavors: ["Helado Cremoso", "Naranja Dulce", "Menta Fresca"],
    effects: ["Euforia Risueña", "Relajación Corporal", "Bienestar Positivo"],
    activities: ["social", "gaming", "creativity"],
    description: "Selección exquisita del clon élite Gelato con un perfume inconfundible a sorbete de cítricos, repostería dulce y menta fresca. Su efecto llena de optimismo y ligereza mental antes de envolver el cuerpo en una calidez sumamente agradable.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #8B5CF6 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "grape-fuel",
    image: "img/grape-fuel.webp",
    name: "Grape Fuel",
    aka: "Grape Pie x Fuel",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 25, cbd: 0.1,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 9, floweringDays: 63,
    rating: 4.9, reviewsCount: 430,
    genetics: "Grape Pie x Fuel",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: { caryophyllene: 45, myrcene: 35, humulene: 20 },
    aroma: "Uvas fermentadas, mosto dulce, queroseno agresivo y resina densa",
    flavors: ["Uva Fermentada", "Combustible Jet-Fuel", "Mosto Dulce"],
    effects: ["Golpe Contundente", "Pesadez Física", "Desconexión"],
    activities: ["relax_sleep", "gaming"],
    description: "Híbrido de tremenda contundencia donde el aroma afrutado de Grape Pie colisiona con el queroseno penetrante de Fuel. Flores extremadamente duras y repletas de tricomas que pegan con fuerza física sedante desde la primera calada.",
    visualColor: "linear-gradient(135deg, #7C2D12 0%, #581C87 100%)",
    bgPattern: "radial-gradient(circle, rgba(124,45,18,0.25) 0%, transparent 70%)"
  },
  {
    id: "hammerhead",
    image: "img/hammerhead.webp",
    name: "Hammerhead",
    aka: "White Rhino x Medicine Man",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 21, cbd: 0.4,
    indicaPct: 80, sativaPct: 20,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 8, floweringDays: 57,
    rating: 4.8, reviewsCount: 410,
    genetics: "White Rhino x Medicine Man",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 50, caryophyllene: 30, pinene: 20 },
    aroma: "Madera húmeda, hachís tradicional afgano, pino y especias",
    flavors: ["Hachís Afgano", "Madera Húmeda", "Especias Picantes"],
    effects: ["Martillo Sedante", "Relajación Muscular Intensa", "Sueño Plácido"],
    activities: ["relax_sleep", "meditation"],
    description: "Bautizada con justicia como 'Cabeza de Martillo' por su demoledor efecto narcótico. Reúne la mítica White Rhino con Medicine Man, produciendo colas densas empapadas en resina terpénica a hachís afgano tradicional.",
    visualColor: "linear-gradient(135deg, #475569 0%, #1E293B 100%)",
    bgPattern: "radial-gradient(circle, rgba(71,85,105,0.25) 0%, transparent 70%)"
  },
  {
    id: "medical-donuts",
    image: "img/medical-donuts.webp",
    name: "Medical Donuts",
    aka: "Donut x Girl Scout Cookies",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 25, cbd: 0.2,
    indicaPct: 50, sativaPct: 50,
    yieldIndoor: 600, yieldOutdoor: 1000,
    floweringWeeks: 9, floweringDays: 60,
    rating: 4.9, reviewsCount: 460,
    genetics: "Donut x Girl Scout Cookies",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 45, caryophyllene: 35, linalool: 20 },
    aroma: "Masa glaseada caliente, vainilla dulce, azúcar moreno y crema",
    flavors: ["Masa Glaseada", "Vainilla Francesa", "Azúcar Tostado"],
    effects: ["Optimismo Creativo", "Felicidad Dulce", "Relax Físico"],
    activities: ["social", "gaming", "creativity"],
    description: "Una auténtica pastelería hecha flor. Su aroma recrea fielmente el glaseado caliente de una rosquilla recién horneada con notas a vainilla francesa y caramelo tostado, complementado con un subidón eufórico muy equilibrado.",
    visualColor: "linear-gradient(135deg, #D97706 0%, #92400E 100%)",
    bgPattern: "radial-gradient(circle, rgba(217,119,6,0.25) 0%, transparent 70%)"
  },
  {
    id: "medical-grape-cbd",
    image: "img/medical-grape-cbd.webp",
    name: "Medical Grape CBD",
    aka: "Grape Selection x Medical CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 0.3, cbd: 15,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 9, floweringDays: 60,
    rating: 4.8, reviewsCount: 350,
    genetics: "Grape Selection x Medical CBD (<0.3% THC)",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, pinene: 35, caryophyllene: 20 },
    aroma: "Golosina de uva morada, bayas silvestres y fondo cítrico suave",
    flavors: ["Gominola de Uva", "Bayas Silvestres", "Cítrico Suave"],
    effects: ["Calma Somática", "Alivio Terapéutico", "Sin Efectos Psicoactivos"],
    activities: ["meditation", "relax_sleep", "nature_walk"],
    description: "Deliciosa variedad rica en CBD puro con notas dulces a gominolas de uva morada. Proporciona una rápida sensación de alivio físico frente a la tensión muscular y el estrés sin producir ningún tipo de efecto psicoactivo.",
    visualColor: "linear-gradient(135deg, #0891B2 0%, #7C3AED 100%)",
    bgPattern: "radial-gradient(circle, rgba(8,145,178,0.25) 0%, transparent 70%)"
  },
  {
    id: "medical-runntz",
    image: "img/medical-runntz.webp",
    name: "Medical Runntz",
    aka: "Zkittlez x Gelato Selección",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 26, cbd: 0.2,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 9, floweringDays: 60,
    rating: 4.9, reviewsCount: 530,
    genetics: "Zkittlez x Gelato (Selección Medical Seeds)",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 45, caryophyllene: 35, myrcene: 20 },
    aroma: "Caramelo tutti-frutti, gas dulce, frutas tropicales ácidas y crema",
    flavors: ["Caramelo Tutti-Frutti", "Gasolina Dulce", "Frutas Tropicales"],
    effects: ["Subidón Eufórico", "Éxtasis Sensorial", "Relajación Aterciopelada"],
    activities: ["social", "gaming", "creativity"],
    description: "La interpretación de Medical Seeds del fenómeno Runtz. Cogollos resinosos en tonos morados con un perfil organoléptico superlativo a golosina tutti-frutti, sorbete tropical y gasolina dulce que provoca un bienestar eufórico incomparable.",
    visualColor: "linear-gradient(135deg, #EC4899 0%, #8B5CF6 100%)",
    bgPattern: "radial-gradient(circle, rgba(236,72,153,0.25) 0%, transparent 70%)"
  },
  {
    id: "mendocino-chanel-kush",
    image: "img/mendocino-chanel-kush.webp",
    name: "Mendocino Chanel Kush",
    aka: "Mendocino Purple Kush x Channel+",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 22, cbd: 0.4,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 8, floweringDays: 53,
    rating: 4.9, reviewsCount: 480,
    genetics: "Mendocino Purple Kush x Channel+",
    origin: "España",
    dominantTerpene: "linalool",
    terpenes: { linalool: 45, myrcene: 35, caryophyllene: 20 },
    aroma: "Perfume floral sofisticado, uva dulce, tierra húmeda y toques Kush",
    flavors: ["Perfume Floral", "Uva Madura", "Kush Terroso"],
    effects: ["Placer Físico Profundo", "Paz Interior", "Calma Duradera"],
    activities: ["relax_sleep", "meditation"],
    description: "Cruce titánico entre las dos genéticas más premiadas de Medical Seeds: Mendocino Purple Kush y Channel+. El resultado es una planta rápida, ultra resinosa y productiva con un sofisticado perfume a flores nobles y uvas maduras.",
    visualColor: "linear-gradient(135deg, #8B5CF6 0%, #4C1D95 100%)",
    bgPattern: "radial-gradient(circle, rgba(139,92,246,0.25) 0%, transparent 70%)"
  },
  {
    id: "og-kush-cbd",
    image: "img/og-kush-cbd.webp",
    name: "OG Kush CBD",
    aka: "OG Kush x Medical CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 10, cbd: 10,
    indicaPct: 30, sativaPct: 70,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 8, floweringDays: 53,
    rating: 4.8, reviewsCount: 390,
    genetics: "OG Kush x Medical CBD (Ratio 1:1)",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 45, caryophyllene: 35, pinene: 20 },
    aroma: "Limón químico penetrante, combustible OG, pino fresco y madera",
    flavors: ["Limón Químico", "Combustible OG", "Pino Resinoso"],
    effects: ["Equilibrio Psíquico", "Alivio del Dolor", "Lucidez Serena"],
    activities: ["social", "nature_walk", "gaming"],
    description: "Todo el sabor legendario a carburante y limón terroso de la auténtica OG Kush californiana combinado en un ratio equilibrado 1:1 (10% THC y 10% CBD) para disfrutar del colocón californiano sin taquicardias ni pesadez.",
    visualColor: "linear-gradient(135deg, #06B6D4 0%, #D97706 100%)",
    bgPattern: "radial-gradient(circle, rgba(6,182,212,0.25) 0%, transparent 70%)"
  },
  {
    id: "over-dawg",
    image: "img/over-dawg.webp",
    name: "Over Dawg",
    aka: "OG Kush x Sour Diesel",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 23, cbd: 0.2,
    indicaPct: 40, sativaPct: 60,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 9, floweringDays: 63,
    rating: 4.8, reviewsCount: 420,
    genetics: "OG Kush x Sour Diesel",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: { caryophyllene: 45, limonene: 35, myrcene: 20 },
    aroma: "Combustible diésel penetrante, cítrico agrio, tierra y almizcle",
    flavors: ["Diésel Penetrante", "Cítrico Agrio", "Almizcle Skunk"],
    effects: ["Estimulación Mental", "Foco Activo", "Vigor Físico"],
    activities: ["workout", "nature_walk", "creativity"],
    description: "Una máquina de vigor y resina nacida del linaje Chemdawg y OG Kush. Ofrece un humo denso cargado de notas a petróleo y cítricos agrios, desatando un efecto dinámico y estimulante que despierta la mente al instante.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #10B981 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "pink-sherbert",
    image: "img/pink-sherbert.webp",
    name: "Pink Sherbert",
    aka: "Pink Panties x Sunset Sherbert",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 24, cbd: 0.2,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 9, floweringDays: 63,
    rating: 4.9, reviewsCount: 450,
    genetics: "Pink Panties x Sunset Sherbert",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: { caryophyllene: 40, limonene: 35, linalool: 25 },
    aroma: "Fresa ácida, cítrico dulce, crema de sorbete y fondo herbal",
    flavors: ["Sorbete de Fresa", "Cítrico Cremoso", "Frutas Rosadas"],
    effects: ["Calma Embriagadora", "Sonrisas y Bienestar", "Desconexión"],
    activities: ["social", "gaming", "relax_sleep"],
    description: "Variedad californiana de flores rosáceas y aroma a sorbete helado de frutos rojos con toques cítricos. Su perfil suave en boca da paso a un estado de sosiego físico profundo y distensión emocional absoluta.",
    visualColor: "linear-gradient(135deg, #EC4899 0%, #BE185D 100%)",
    bgPattern: "radial-gradient(circle, rgba(236,72,153,0.25) 0%, transparent 70%)"
  },
  {
    id: "recovery-cbd",
    image: "img/recovery-cbd.webp",
    name: "Recovery CBD",
    aka: "Medical CBD x Therapy CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 0.3, cbd: 21,
    indicaPct: 50, sativaPct: 50,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 8, floweringDays: 56,
    rating: 4.9, reviewsCount: 380,
    genetics: "Medical CBD x Therapy CBD (Ratio 1:70)",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 50, caryophyllene: 30, pinene: 20 },
    aroma: "Melocotón maduro, toques herbales de manzanilla y fondo terroso",
    flavors: ["Melocotón Dulce", "Manzanilla Floral", "Terroso Suave"],
    effects: ["Recuperación Muscular", "Reducción de Inflamación", "Sueño Reparador"],
    activities: ["relax_sleep", "meditation", "workout"],
    description: "El récord terapéutico del banco con un descomunal 21% de CBD y menos del 0.3% de THC. Diseñada especialmente para deportistas y pacientes que buscan regeneración muscular y alivio somático sin alteración cognitiva.",
    visualColor: "linear-gradient(135deg, #06B6D4 0%, #059669 100%)",
    bgPattern: "radial-gradient(circle, rgba(6,182,212,0.25) 0%, transparent 70%)"
  },
  {
    id: "red-cross-cbd",
    image: "img/red-cross-cbd.webp",
    name: "Red Cross CBD",
    aka: "Lambsbread x Medical CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 0.2, cbd: 10,
    indicaPct: 80, sativaPct: 20,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 8, floweringDays: 56,
    rating: 4.8, reviewsCount: 340,
    genetics: "Lambsbread x Medical CBD (<0.2% THC)",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, pinene: 35, caryophyllene: 20 },
    aroma: "Fruta confitada, fresas silvestres, flores rojas y fondo Skunk suave",
    flavors: ["Fruta Confitada", "Fresas Silvestres", "Floral Skunk"],
    effects: ["Alivio Terapéutico Sin Psicoactividad", "Calma Mental", "Relajación"],
    activities: ["meditation", "relax_sleep"],
    description: "Una bella variedad médica de cogollos escarchados con tonos rojizos. Su buqué a frutas confitadas y fresas silvestres la convierte en un placer para el paladar mientras su perfil de CBD garantiza una relajación corporal ininterrumpida.",
    visualColor: "linear-gradient(135deg, #EF4444 0%, #991B1B 100%)",
    bgPattern: "radial-gradient(circle, rgba(239,68,68,0.25) 0%, transparent 70%)"
  },
  {
    id: "some-sweet",
    image: "img/some-sweet.webp",
    name: "Some Sweet",
    aka: "Bluehell x Grapefruit",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 20, cbd: 0.3,
    indicaPct: 80, sativaPct: 20,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 8, floweringDays: 53,
    rating: 4.8, reviewsCount: 370,
    genetics: "Bluehell x Grapefruit",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 45, myrcene: 35, pinene: 20 },
    aroma: "Pomelo rosado dulce, golosina de arándano y fondo afrutado fresco",
    flavors: ["Pomelo Rosado", "Arándano Dulce", "Gominola Cítrica"],
    effects: ["Placer Relajante", "Bienestar Afable", "Tranquilidad"],
    activities: ["social", "relax_sleep", "gaming"],
    description: "Cruce delicioso entre Bluehell y la refrescante Grapefruit. Desarrolla cogollos densos bañados en aromas cítricos a pomelo y gominola de frutos azules, con una floración exprés de apenas 53 días.",
    visualColor: "linear-gradient(135deg, #F43F5E 0%, #BE123C 100%)",
    bgPattern: "radial-gradient(circle, rgba(244,63,94,0.25) 0%, transparent 70%)"
  },
  {
    id: "sour-glue",
    image: "img/sour-glue.webp",
    name: "Sour Glue",
    aka: "Sour Diesel x Gorilla Glue #4",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 25, cbd: 0.2,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 9, floweringDays: 60,
    rating: 4.9, reviewsCount: 510,
    genetics: "Sour Diesel x Gorilla Glue #4",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: { caryophyllene: 45, limonene: 35, myrcene: 20 },
    aroma: "Gasolina ácida penetrante, pegamento industrial, pino y tierra",
    flavors: ["Gasolina Ácida", "Pegamento GG4", "Pino Terroso"],
    effects: ["Impacto Demoledor", "Inmovilización Agradable", "Euforia Inicial"],
    activities: ["relax_sleep", "gaming"],
    description: "Una colisión brutal entre dos de las genéticas más resinosas y potentes de Estados Unidos. Resina pegajosa que desborda las tijeras de manicurado con un perfume penetrante a pegamento industrial y queroseno ácido.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #047857 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "strawberry-cake-cbd",
    image: "img/strawberry-cake-cbd.webp",
    name: "Strawberry Cake CBD",
    aka: "Strawberry Selection x Medical CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 0.3, cbd: 15,
    indicaPct: 40, sativaPct: 60,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 10, floweringDays: 70,
    rating: 4.8, reviewsCount: 350,
    genetics: "Strawberry Selection x Medical CBD (<0.3% THC)",
    origin: "España",
    dominantTerpene: "myrcene",
    terpenes: { myrcene: 45, terpinolene: 35, pinene: 20 },
    aroma: "Pastel de fresas con nata, masa dulce horneada y vainilla",
    flavors: ["Pastel de Fresas", "Nata Montada", "Vainilla Dulce"],
    effects: ["Alivio Terapéutico", "Serenidad Mental", "Antiestrés"],
    activities: ["nature_walk", "creativity", "meditation"],
    description: "Un dulce postre en forma de flor medicinal. Con un 15% de CBD y menos de 0.3% de THC, regala un aroma embriagador a tarta de fresas con nata montada mientras alivia la tensión muscular de forma suave y limpia.",
    visualColor: "linear-gradient(135deg, #EC4899 0%, #06B6D4 100%)",
    bgPattern: "radial-gradient(circle, rgba(236,72,153,0.25) 0%, transparent 70%)"
  },
  {
    id: "superfruit-cbd",
    image: "img/superfruit-cbd.webp",
    name: "Superfruit CBD",
    aka: "Superfruit Selection x Medical CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 0.3, cbd: 12,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 10, floweringDays: 67,
    rating: 4.8, reviewsCount: 330,
    genetics: "Superfruit Selection x Medical CBD (<0.3% THC)",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 45, myrcene: 35, pinene: 20 },
    aroma: "Cóctel de frutas exóticas, maracuyá, mango maduro y cítricos dulces",
    flavors: ["Frutas Exóticas", "Maracuyá Ácida", "Mango Dulce"],
    effects: ["Bienestar Corporal", "Claridad y Buen Humor", "Cero Psicoactividad"],
    activities: ["social", "nature_walk", "meditation"],
    description: "Un estallido multivitamínico de frutas tropicales en cogollos carnosos y resinosos. Excelente variedad para consumir a lo largo del día manteniendo un rendimiento cognitivo óptimo y una sensación corporal relajada.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #0891B2 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "y-griega-cbd",
    image: "img/y-griega-cbd.webp",
    name: "Y Griega CBD",
    aka: "Y Griega x Crew CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Sativa",
    thc: 10, cbd: 10,
    indicaPct: 30, sativaPct: 70,
    yieldIndoor: 500, yieldOutdoor: 400,
    floweringWeeks: 10, floweringDays: 68,
    rating: 4.9, reviewsCount: 460,
    genetics: "Y Griega x Crew CBD (Ratio 1:1)",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 45, myrcene: 30, pinene: 25 },
    aroma: "Cítrico alimonado Haze, incienso fino, madera de sándalo y almizcle",
    flavors: ["Limón Haze", "Incienso Catedralicio", "Sándalo Amaderado"],
    effects: ["Efecto Terapéutico Lúcido", "Alivio Físico Sin Ansiedad", "Claridad Creativa"],
    activities: ["creativity", "social", "gaming"],
    description: "El clásico medicinal 1:1 más célebre de Medical Seeds en colaboración con CBD Crew. Mantiene la chispa alimonada e incensada de Y Griega con una equilibrada carga de CBD que modula el efecto eliminando cualquier rastro de ansiedad.",
    visualColor: "linear-gradient(135deg, #F59E0B 0%, #06B6D4 100%)",
    bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
  },
  {
    id: "y-griega-cbd-2-0",
    image: "img/y-griega-cbd-2-0.webp",
    name: "Y Griega CBD 2.0",
    aka: "Y Griega x Medical CBD",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Híbrida",
    thc: 6, cbd: 12,
    indicaPct: 50, sativaPct: 50,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 10, floweringDays: 70,
    rating: 4.8, reviewsCount: 380,
    genetics: "Y Griega x Medical CBD (Ratio 1:2)",
    origin: "España",
    dominantTerpene: "limonene",
    terpenes: { limonene: 40, myrcene: 35, pinene: 25 },
    aroma: "Limón maduro, flores silvestres, incienso ligero y fondo balsámico",
    flavors: ["Limón Maduro", "Bouquet Floral", "Incienso Suave"],
    effects: ["Alivio Profundo de Ansiedad", "Tranquilidad Terapéutica", "Enfoque Despejado"],
    activities: ["meditation", "nature_walk", "relax_sleep"],
    description: "Versión 2.0 optimizada con un ratio 1:2 (THC 6% : CBD 12%) que potencia la faceta sedante y ansiolítica de la planta. Aroma fresco y floral muy limpio que ayuda a desconectar el sistema nervioso tras jornadas intensas.",
    visualColor: "linear-gradient(135deg, #10B981 0%, #0891B2 100%)",
    bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
  },
  {
    id: "zkittlez",
    image: "img/zkittlez.webp",
    name: "Zkittlez",
    aka: "Grape Ape x Grapefruit Selección Original",
    bank: "Medical Seeds",
    breeder: "Medical Seeds",
    species: "Indica",
    thc: 22, cbd: 0.2,
    indicaPct: 70, sativaPct: 30,
    yieldIndoor: 500, yieldOutdoor: 700,
    floweringWeeks: 10, floweringDays: 70,
    rating: 4.9, reviewsCount: 540,
    genetics: "Grape Ape x Grapefruit (Selección Medical Seeds)",
    origin: "España",
    dominantTerpene: "caryophyllene",
    terpenes: { caryophyllene: 45, limonene: 35, humulene: 20 },
    aroma: "Caramelos masticables de frutas tropicales, uva dulce y fondo cítrico",
    flavors: ["Caramelo de Frutas", "Uva Dulce", "Cítrico Tropical"],
    effects: ["Felicidad Eufórica", "Relajación Suave", "Paz Sensorial"],
    activities: ["social", "gaming", "relax_sleep"],
    description: "La famosa genética de los caramelos de fruta seleccionada y estabilizada por Medical Seeds. Cogollos gruesos y escarchados que desprenden un perfume irresistible a golosina masticable de uva y frutas exóticas con una dicha física apacible.",
    visualColor: "linear-gradient(135deg, #EC4899 0%, #F59E0B 100%)",
    bgPattern: "radial-gradient(circle, rgba(236,72,153,0.25) 0%, transparent 70%)"
  }
];
