import sys
sys.stdout.reconfigure(encoding='utf-8')

new_strains = '''      },
      {
        id: "nirvana-aurora-indica",
        image: "img/nirvana-aurora-indica.webp",
        name: "Aurora Indica",
        aka: "Aurora Pure Indica",
        bank: "Nirvana Seeds",
        species: "Indica",
        thc: 20, cbd: 0.8,
        yieldIndoor: 500, yieldOutdoor: 600,
        floweringDays: 60, rating: 4.8, reviewsCount: 1450,
        genetics: "Afghan x Northern Lights",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "myrcene",
        terpenes: { myrcene: 50, caryophyllene: 30, pinene: 20 },
        flavors: ["Hachís Especiado", "Tierra Húmeda", "Café Tostado"],
        effects: ["Sedación Corporal Profunda", "Alivio del Dolor", "Sueño Reparador"],
        activities: ["sleep", "meditation", "relax"],
        description: "Aurora Indica es una de las índicas más potentes y narcóticas del catálogo histórico de Nirvana Seeds. Híbrida 90% índica resultante de cruzar Northern Lights con Afghan, produce cogollos densos como rocas, empapados de resina brillante con aromas a hachís terroso, café y especias oscuras. Efecto couchlock demoledor idóneo para combatir el insomnio crónico y dolores intensos.",
        visualColor: "linear-gradient(135deg, #1E1B4B 0%, #4338CA 100%)",
        bgPattern: "radial-gradient(circle, rgba(67,56,202,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-bubblelicious",
        image: "img/nirvana-bubblelicious.webp",
        name: "Bubblelicious",
        aka: "Nirvana Bubblegum",
        bank: "Nirvana Seeds",
        species: "Hybrid",
        thc: 18, cbd: 0.5,
        yieldIndoor: 500, yieldOutdoor: 650,
        floweringDays: 63, rating: 4.8, reviewsCount: 1680,
        genetics: "Indiana Bubblegum x Nirvana Secret Hybrid",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "myrcene",
        terpenes: { myrcene: 45, limonene: 30, caryophyllene: 25 },
        flavors: ["Chicle de Fresa", "Dulce Azucarado", "Frutas Rosas"],
        effects: ["Euforia Alegre", "Relajación Placentera", "Sonrisa Duradera"],
        activities: ["social", "music", "gaming", "relax"],
        description: "Bubblelicious es el legendario tributo de Nirvana Seeds a la mítica Bubblegum desarrollada originalmente en Indiana en los años 90 y perfeccionada en Holanda. Famosa mundialmente por su sabor inconfundible a chicle dulce de fresa y golosinas azucaradas. Produce cogollos cargados de tricomas y un efecto eufórico inicial que desemboca en un bienestar físico relajante y alegre.",
        visualColor: "linear-gradient(135deg, #F43F5E 0%, #FB7185 100%)",
        bgPattern: "radial-gradient(circle, rgba(244,63,94,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-master-kush",
        image: "img/nirvana-master-kush.webp",
        name: "Master Kush",
        aka: "High Times Cannabis Cup Winner Kush",
        bank: "Nirvana Seeds",
        species: "Indica",
        thc: 22, cbd: 0.9,
        yieldIndoor: 500, yieldOutdoor: 600,
        floweringDays: 58, rating: 4.9, reviewsCount: 1890,
        genetics: "Hindu Kush x Hindu Kush Pure Landraces",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "myrcene",
        terpenes: { myrcene: 50, caryophyllene: 28, limonene: 22 },
        flavors: ["Tierra Kush", "Pino Cítrico", "Madera Noble"],
        effects: ["Paz Mental", "Relajación Muscular Intensa", "Calma Serena"],
        activities: ["meditation", "sleep", "relax"],
        description: "Master Kush de Nirvana Seeds es un clásico atemporal de los coffee shops holandeses y doble ganadora de la High Times Cannabis Cup. Criada a partir de dos landraces autóctonas del valle del Hindu Kush, conserva toda la pureza botánica afgana: porte compacto, flores resinosas aromáticas a pino terroso y toques cítricos, y un efecto de serenidad corporal absoluta sin nublar el intelecto.",
        visualColor: "linear-gradient(135deg, #15803D 0%, #166534 100%)",
        bgPattern: "radial-gradient(circle, rgba(21,128,61,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-ak-48",
        image: "img/nirvana-ak-48.webp",
        name: "AK-48",
        aka: "Nirvana 48-Hour Blast",
        bank: "Nirvana Seeds",
        species: "Hybrid",
        thc: 20, cbd: 0.4,
        yieldIndoor: 500, yieldOutdoor: 650,
        floweringDays: 50, rating: 4.8, reviewsCount: 1950,
        genetics: "Colombian Gold x Mexican x Thai x Afghani",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "caryophyllene",
        terpenes: { caryophyllene: 40, myrcene: 35, terpinolene: 25 },
        flavors: ["Dulce Floral", "Toque Especiado", "Madera Fresca"],
        effects: ["Pegada Rápida", "Claridad Cerebral", "Energía Equilibrada"],
        activities: ["creative", "social", "gaming"],
        description: "AK-48 es uno de los buques insignia más vendidos de Nirvana Seeds desde finales de los 90. Creada cruzando cuatro genéticas legendarias (Colombian, Mexican, Thai y Afghani), destaca por su velocidad de floración casi récord (puede estar lista en tan solo 48 a 50 días) y un colocón cerebral de impacto inmediato, limpio, inspirador y social, con aroma floral dulce y fondo especiado.",
        visualColor: "linear-gradient(135deg, #D97706 0%, #B45309 100%)",
        bgPattern: "radial-gradient(circle, rgba(217,119,6,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-wonder-woman",
        image: "img/nirvana-wonder-woman.webp",
        name: "Wonder Woman",
        aka: "Nirvana Wonder Heavy Producer",
        bank: "Nirvana Seeds",
        species: "Hybrid",
        thc: 21, cbd: 0.6,
        yieldIndoor: 600, yieldOutdoor: 750,
        floweringDays: 63, rating: 4.7, reviewsCount: 1280,
        genetics: "White Widow x Top Skunk x Ice",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "limonene",
        terpenes: { limonene: 42, myrcene: 35, caryophyllene: 23 },
        flavors: ["Skunk Dulce", "Queroseno Diésel", "Cítrico Fresco"],
        effects: ["Elevación Duradera", "Relajación Contemplativa", "Optimismo"],
        activities: ["creative", "relax", "music"],
        description: "Wonder Woman de Nirvana Seeds es una productora masiva de cogollos duros como piedras, nacida del linaje elite de White Widow y cepas Skunk de alto rendimiento. Sus flores destacan por un perfil aromático intenso a Skunk dulce con notas ácidas y gasolina diésel, entregando una experiencia reconfortante de optimismo mental acompañada de un relajante descanso físico.",
        visualColor: "linear-gradient(135deg, #0284C7 0%, #0369A1 100%)",
        bgPattern: "radial-gradient(circle, rgba(2,132,199,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-somango-xxl",
        image: "img/nirvana-somango-xxl.webp",
        name: "Somango XXL",
        aka: "The Mango Beast",
        bank: "Nirvana Seeds",
        species: "Hybrid",
        thc: 19, cbd: 0.5,
        yieldIndoor: 650, yieldOutdoor: 800,
        floweringDays: 65, rating: 4.8, reviewsCount: 1540,
        genetics: "Somango (Jack Herer x Super Skunk x Big Skunk Korean) x Critical+",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "myrcene",
        terpenes: { myrcene: 55, pinene: 25, limonene: 20 },
        flavors: ["Mango Maduro", "Ensalada Tropical", "Tierra Dulce"],
        effects: ["Calma Creativa", "Lucidez Placentera", "Relajación Zen"],
        activities: ["art", "reading", "relax", "sunset"],
        description: "Somango XXL de Nirvana Seeds es una versión perfeccionada y sobrealimentada en rendimiento de la aclamada genética Somango. Destaca por un despliegue terpénico tropical dominado por mango jugoso maduro y frutas exóticas sobre fondo dulce. Su efecto proporciona una lúcida estimulación mental creativa junto a una sedosa relajación muscular sin letargo.",
        visualColor: "linear-gradient(135deg, #EA580C 0%, #C2410C 100%)",
        bgPattern: "radial-gradient(circle, rgba(234,88,12,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-papaya",
        image: "img/nirvana-papaya.webp",
        name: "Papaya",
        aka: "Nirvana Tropical Papaya",
        bank: "Nirvana Seeds",
        species: "Indica",
        thc: 20, cbd: 0.7,
        yieldIndoor: 450, yieldOutdoor: 550,
        floweringDays: 60, rating: 4.9, reviewsCount: 1720,
        genetics: "Jock Horror x Skunk #1",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "myrcene",
        terpenes: { myrcene: 48, caryophyllene: 30, limonene: 22 },
        flavors: ["Papaya Dulce", "Fruta Tropical Picante", "Notas Almizcladas"],
        effects: ["Paz Corporal Plena", "Desconexión Mental", "Apetito Saciante"],
        activities: ["movie", "sleep", "relax"],
        description: "Papaya es una de las variedades más apreciadas y distintivas del repertorio clásico de Nirvana Seeds. Híbrida de predominancia índica de maduración rápida que despunta por su inconfundible fragancia a papaya madura, fruta de la pasión y toques almizclados picantes. Su colocón es predominantemente físico, calmante y analgésico, excelente para desconectar de tensiones cotidianas.",
        visualColor: "linear-gradient(135deg, #F59E0B 0%, #D97706 100%)",
        bgPattern: "radial-gradient(circle, rgba(245,158,11,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-hawaii-maui-waui",
        image: "img/nirvana-hawaii-maui-waui.webp",
        name: "Hawaii Maui Waui",
        aka: "Maui Wowie Old School Sativa",
        bank: "Nirvana Seeds",
        species: "Sativa",
        thc: 19, cbd: 0.4,
        yieldIndoor: 450, yieldOutdoor: 600,
        floweringDays: 70, rating: 4.8, reviewsCount: 1610,
        genetics: "Hawaiian Sativa Landrace Inbred Line",
        origin: "Islas Hawái / Ámsterdam",
        dominantTerpene: "myrcene",
        terpenes: { myrcene: 40, pinene: 35, limonene: 25 },
        flavors: ["Piña Cítrica", "Brisa Tropical", "Hierba Dulce"],
        effects: ["Euforia Tropical", "Inspiración Creativa", "Chute de Energía Positiva"],
        activities: ["outdoor", "beach", "creative", "social"],
        description: "Hawaii Maui Waui es la joya tropical de Nirvana Seeds capturando la esencia de la legendaria sativa isleña de los años 70. Desarrollada y estabilizada a lo largo de años de selección genética, ofrece una experiencia viva y brillante con marcados aromas a piña colada, frutas cítricas y hierba fresca. Su efecto es un estallido de euforia soleada, claridad y ligereza física.",
        visualColor: "linear-gradient(135deg, #10B981 0%, #059669 100%)",
        bgPattern: "radial-gradient(circle, rgba(16,185,129,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-super-skunk",
        image: "img/nirvana-super-skunk.webp",
        name: "Super Skunk",
        aka: "Nirvana Super Skunk Supreme",
        bank: "Nirvana Seeds",
        species: "Hybrid",
        thc: 20, cbd: 0.8,
        yieldIndoor: 550, yieldOutdoor: 700,
        floweringDays: 60, rating: 4.8, reviewsCount: 1840,
        genetics: "Skunk #1 x Afghani Hash Plant",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "myrcene",
        terpenes: { myrcene: 48, caryophyllene: 32, pinene: 20 },
        flavors: ["Skunk Penetrante", "Almizcle Terroso", "Pungencia Dulce"],
        effects: ["Relajación Muscular", "Alivio del Estrés", "Buen Humor"],
        activities: ["relax", "social", "music"],
        description: "Super Skunk de Nirvana Seeds es una de las reinterpretaciones más respetadas del histórico cruce entre Skunk #1 y una robusta Afghani pura. Reconocida por su extrema facilidad de cultivo, cosechas pesadas de cogollos resinosos y un perfil organoléptico super penetrante de aromas skunky, almizcle y dulzura terrosa. Proporciona una relajación reconfortante y duradera.",
        visualColor: "linear-gradient(135deg, #65A30D 0%, #4D7C0F 100%)",
        bgPattern: "radial-gradient(circle, rgba(101,163,13,0.25) 0%, transparent 70%)"
      },
      {
        id: "nirvana-blackjack",
        image: "img/nirvana-blackjack.webp",
        name: "Blackjack",
        aka: "Nirvana Black Jack F1",
        bank: "Nirvana Seeds",
        species: "Hybrid",
        thc: 22, cbd: 0.7,
        yieldIndoor: 500, yieldOutdoor: 650,
        floweringDays: 65, rating: 4.8, reviewsCount: 1510,
        genetics: "Black Domino x Jock Horror",
        origin: "Ámsterdam, Países Bajos",
        dominantTerpene: "caryophyllene",
        terpenes: { caryophyllene: 40, myrcene: 35, terpinolene: 25 },
        flavors: ["Pino Resinoso", "Pimienta Negra", "Hachís Dulce"],
        effects: ["Claridad Mental Robusta", "Vigor Físico", "Calma Duradera"],
        activities: ["gaming", "creative", "social", "reading"],
        description: "Blackjack es una de las creaciones más prestigiosas y potentes de Nirvana Seeds, lograda al fusionar la legendaria Black Domino con la vigorosa Jock Horror (híbrida Jack Herer). Presenta flores gruesas y resinosas con un aroma complejo que combina madera de pino, bayas silvestres y notas picantes a pimienta negra. Proporciona un colocón potente y balanceado que estimula la creatividad.",
        visualColor: "linear-gradient(135deg, #374151 0%, #1F2937 100%)",
        bgPattern: "radial-gradient(circle, rgba(55,65,81,0.25) 0%, transparent 70%)"
'''

with open('js/data.js', 'r', encoding='utf-8') as f:
    content = f.read()

target = '        bgPattern: "radial-gradient(circle, rgba(100,116,139,0.2) 0%, transparent 70%)"\n      },\n  {\n      id: "dna-kosher-kush",'
replacement = '        bgPattern: "radial-gradient(circle, rgba(100,116,139,0.2) 0%, transparent 70%)"\n' + new_strains + '      },\n  {\n      id: "dna-kosher-kush",'

if target in content:
    content = content.replace(target, replacement, 1)
    with open('js/data.js', 'w', encoding='utf-8') as f:
        f.write(content)
    print("✅ Inserción exitosa de las 10 cepas de Nirvana Seeds en js/data.js!")
else:
    print("❌ Error: no se encontró el target exacto en js/data.js")
