import re
import sys

sys.stdout.reconfigure(encoding='utf-8')

new_strains = [
    # --- DELICIOUS SEEDS ---
    {
        "id": "sugar-black-rose",
        "image": "images/strains/sugar-black-rose.jpg",
        "name": "Sugar Black Rose",
        "aka": "SBR Legend",
        "bank": "Delicious Seeds",
        "species": "Índica",
        "indicaPct": 80,
        "sativaPct": 20,
        "thc": 25,
        "cbd": 0.2,
        "yieldIndoor": 450,
        "yieldOutdoor": 900,
        "floweringDays": 53,
        "rating": 4.9,
        "reviewsCount": 1620,
        "lineage": "Critical Mass x Black Domina 98",
        "genetics": "Critical Mass x Black Domina 98",
        "origin": "España",
        "dominantTerpene": "myrcene",
        "terpenes": {"myrcene": 55, "caryophyllene": 25, "pinene": 20},
        "aroma": "Uva madura, flores dulces y fondo terroso",
        "flavor": ["Uva madura", "Flores dulces", "Terroso", "Almizcle"],
        "effects": ["Relajación corporal profunda", "Paz mental", "Efecto narcótico", "Alivio analgésico"],
        "difficulty": "Fácil",
        "description": "Sugar Black Rose de Delicious Seeds es una de las índicas más laureadas y sabrosas de la historia del cannabis en España. Cruce magistral de Critical Mass con la mítica Black Domina 98 que produce cogollos ultradensos cargados de resina brillante con bouquet a uva madura y flores dulces sobre fondo terroso noble.",
        "gradient": "linear-gradient(135deg, #1b0a2a 0%, #3a1548 50%, #10B981 100%)",
        "activities": ["Descanso nocturno", "Lectura tranquila", "Desconexión", "Alivio del estrés"]
    },
    {
        "id": "eleven-roses",
        "image": "images/strains/eleven-roses.jpg",
        "name": "Eleven Roses",
        "aka": "Eleven Roses Elite",
        "bank": "Delicious Seeds",
        "species": "Índica",
        "indicaPct": 100,
        "sativaPct": 0,
        "thc": 24,
        "cbd": 0.2,
        "yieldIndoor": 600,
        "yieldOutdoor": 1000,
        "floweringDays": 55,
        "rating": 4.9,
        "reviewsCount": 1410,
        "lineage": "Appalachian Kush x Sugar Black Rose",
        "genetics": "Appalachian Kush x Sugar Black Rose",
        "origin": "España",
        "dominantTerpene": "caryophyllene",
        "terpenes": {"caryophyllene": 50, "myrcene": 30, "humulene": 20},
        "aroma": "Frutas metálicas, tierra húmeda y fondo kush",
        "flavor": ["Frutas metálicas", "Tierra húmeda", "Kush noble", "Pimienta"],
        "effects": ["Sedación física masiva", "Pesadez muscular", "Couchlock placentero", "Calma mental"],
        "difficulty": "Fácil",
        "description": "Eleven Roses es la obra maestra índica pura de Delicious Seeds, lograda al mejorar la premiada Sugar Black Rose con el polen selecto de un macho Appalachian Kush. Exhibe tonalidades otoñales oscuras y un rendimiento descomunal de flores repletas de tricomas con aroma a tierra húmeda y fondo Kush.",
        "gradient": "linear-gradient(135deg, #18101a 0%, #421a32 50%, #10B981 100%)",
        "activities": ["Sueño reparador", "Películas nocturnas", "Recuperación física", "Meditación"]
    },
    {
        "id": "golosa",
        "image": "images/strains/golosa.jpg",
        "name": "Golosa",
        "aka": "Delicious Dark Gem",
        "bank": "Delicious Seeds",
        "species": "Índica",
        "indicaPct": 80,
        "sativaPct": 20,
        "thc": 26,
        "cbd": 0.1,
        "yieldIndoor": 550,
        "yieldOutdoor": 800,
        "floweringDays": 60,
        "rating": 4.8,
        "reviewsCount": 1180,
        "lineage": "Bay 11 x Grapefruit x Blueberry",
        "genetics": "Bay 11 x Grapefruit x Blueberry",
        "origin": "España",
        "dominantTerpene": "myrcene",
        "terpenes": {"myrcene": 45, "caryophyllene": 35, "limonene": 20},
        "aroma": "Frutos del bosque oscuros, café amargo y menta",
        "flavor": ["Frutos del bosque", "Café amargo", "Menta refrescante", "Tomillo"],
        "effects": ["Euforia embriagadora inicial", "Relajación duradera", "Alivio de tensiones", "Bienestar"],
        "difficulty": "Media",
        "description": "Golosa de Delicious Seeds es una de las creaciones más exóticas y potentes del banco, alcanzando hasta un 26% de THC. Destaca por sus hojas casi negras y sus cálices impregnados de aromas complejos a frutas del bosque maduras, toques tostados a café y un final fresco mentolado.",
        "gradient": "linear-gradient(135deg, #110e1c 0%, #2f1947 50%, #10B981 100%)",
        "activities": ["Desconexión sensorial", "Música envolvente", "Fin de jornada", "Alivio de migrañas"]
    },
    {
        "id": "marmalate",
        "image": "images/strains/marmalate.jpg",
        "name": "Marmalate",
        "aka": "Critical x Lavender Marmalade",
        "bank": "Delicious Seeds",
        "species": "Híbrida",
        "indicaPct": 70,
        "sativaPct": 30,
        "thc": 21,
        "cbd": 0.3,
        "yieldIndoor": 500,
        "yieldOutdoor": 600,
        "floweringDays": 53,
        "rating": 4.8,
        "reviewsCount": 1340,
        "lineage": "Critical Mass x Lavender",
        "genetics": "Critical Mass x Lavender",
        "origin": "España",
        "dominantTerpene": "limonene",
        "terpenes": {"limonene": 45, "myrcene": 35, "linalool": 20},
        "aroma": "Mermelada de uva dulce, lavanda y piruleta",
        "flavor": ["Mermelada de uva", "Lavanda floral", "Golosina de fresa", "Dulce"],
        "effects": ["Estimulación cerebral alegre", "Relajación corporal suave", "Claridad lúcida", "Sociabilidad"],
        "difficulty": "Muy fácil",
        "description": "Marmalate es una hibridación sobresaliente entre el vigor productivo de Critical Mass y el refinado aroma floral afrutado de Lavender. Floración ultrarrápida de menos de 8 semanas, cogollos compactos como piedras y un sabor dulce a confitura de uva con notas de lavanda.",
        "gradient": "linear-gradient(135deg, #260d29 0%, #561652 50%, #10B981 100%)",
        "activities": ["Reuniones entre amigos", "Conversación creativa", "Tardes relajadas", "Cocinar"]
    },
    {
        "id": "cotton-candy-kush",
        "image": "images/strains/cotton-candy-kush.jpg",
        "name": "Cotton Candy Kush",
        "aka": "Cotton Candy Sweet Sativa",
        "bank": "Delicious Seeds",
        "species": "Sativa",
        "indicaPct": 25,
        "sativaPct": 75,
        "thc": 23,
        "cbd": 0.3,
        "yieldIndoor": 550,
        "yieldOutdoor": 700,
        "floweringDays": 65,
        "rating": 4.8,
        "reviewsCount": 1220,
        "lineage": "Lavender x Power Plant",
        "genetics": "Lavender x South African Power Plant",
        "origin": "España / Sudáfrica",
        "dominantTerpene": "terpinolene",
        "terpenes": {"terpinolene": 45, "myrcene": 30, "caryophyllene": 25},
        "aroma": "Algodón de azúcar, cítrico floral y fondo metálico",
        "flavor": ["Algodón de azúcar", "Cítrico dulce", "Flores frescas", "Toque metálico"],
        "effects": ["Euforia enérgica", "Creatividad expansiva", "Risas contagiosas", "Vitalidad sin nerviosismo"],
        "difficulty": "Media",
        "description": "Cotton Candy Kush fusiona el perfil aromático de Lavender con la potencia sativa arrolladora de la sudafricana Power Plant. Sus flores desprenden una fragancia irresistible a feria y algodón de azúcar azucarado con matices cítricos florales. Subidón estimulante y muy creativo.",
        "gradient": "linear-gradient(135deg, #0e1e24 0%, #154c5e 50%, #10B981 100%)",
        "activities": ["Arte y diseño", "Composición musical", "Paseos al aire libre", "Socializar"]
    },
    {
        "id": "caramelo",
        "image": "images/strains/caramelo.jpg",
        "name": "Caramelo",
        "aka": "Lavender Selection Pure Passion",
        "bank": "Delicious Seeds",
        "species": "Sativa",
        "indicaPct": 30,
        "sativaPct": 70,
        "thc": 24,
        "cbd": 0.2,
        "yieldIndoor": 450,
        "yieldOutdoor": 500,
        "floweringDays": 63,
        "rating": 4.7,
        "reviewsCount": 1090,
        "lineage": "Selección Lavender x Lavender",
        "genetics": "Super Skunk x Big Skunk Korean x Afghani x Hawaiian",
        "origin": "España",
        "dominantTerpene": "limonene",
        "terpenes": {"limonene": 45, "caryophyllene": 30, "linalool": 25},
        "aroma": "Nuez moscada, caramelo dulce y fondo floral Skunk",
        "flavor": ["Caramelo dulce", "Nuez moscada", "Skunk floral", "Vainilla especiada"],
        "effects": ["Euforia lúcida", "Empuje anímico positivo", "Bienestar placentero", "Relajación armoniosa"],
        "difficulty": "Media",
        "description": "Caramelo nace de una estricta selección entre fenotipos de Lavender con marcados rasgos sativas. Desarrolla ramas vigorosas con tonalidades violetas en floración y flores cargadas de resina con una exquisita fragancia a dulce de caramelo, especias cálidas y nuez moscada.",
        "gradient": "linear-gradient(135deg, #2b170c 0%, #613414 50%, #10B981 100%)",
        "activities": ["Proyectos diurnos", "Actividades recreativas", "Conversación", "Paseos soleados"]
    },
    {
        "id": "critical-kali-mist",
        "image": "images/strains/critical-kali-mist.jpg",
        "name": "Critical Kali Mist",
        "aka": "Critical Haze Queen",
        "bank": "Delicious Seeds",
        "species": "Sativa",
        "indicaPct": 20,
        "sativaPct": 80,
        "thc": 22,
        "cbd": 0.3,
        "yieldIndoor": 500,
        "yieldOutdoor": 800,
        "floweringDays": 65,
        "rating": 4.8,
        "reviewsCount": 980,
        "lineage": "Critical Mass x Kali Mist",
        "genetics": "Critical Mass x Kali Mist Elite",
        "origin": "España",
        "dominantTerpene": "terpinolene",
        "terpenes": {"terpinolene": 50, "pinene": 30, "myrcene": 20},
        "aroma": "Incienso puro, madera noble y notas metálicas",
        "flavor": ["Incienso catedralicio", "Madera noble", "Notas metálicas Haze", "Pino"],
        "effects": ["Claridad cerebral total", "Energía chispeante", "Inspiración artística", "Antidepresivo"],
        "difficulty": "Media",
        "description": "Critical Kali Mist une la legendaria reina de las sativas Kali Mist con la rapidez y densidad productiva de Critical Mass. Ofrece largas colas de cogollos resinosos cargados de terpenos inciensados de iglesia, madera añeja y notas metálicas, con un efecto cerebral diáfano y revitalizante.",
        "gradient": "linear-gradient(135deg, #102418 0%, #1c5234 50%, #10B981 100%)",
        "activities": ["Brainstorming", "Trabajo creativo", "Senderismo", "Ejercicio moderado"]
    },
    {
        "id": "unknown-kush",
        "image": "images/strains/unknown-kush.jpg",
        "name": "Unknown Kush",
        "aka": "Desconocida Kush",
        "bank": "Delicious Seeds",
        "species": "Híbrida",
        "indicaPct": 50,
        "sativaPct": 50,
        "thc": 23,
        "cbd": 0.2,
        "yieldIndoor": 500,
        "yieldOutdoor": 800,
        "floweringDays": 60,
        "rating": 4.8,
        "reviewsCount": 1150,
        "lineage": "Bay 11 x Clon Élite Unknown Kush",
        "genetics": "Bay 11 x Desconocida Kush Elite",
        "origin": "España / EE.UU.",
        "dominantTerpene": "caryophyllene",
        "terpenes": {"caryophyllene": 45, "limonene": 30, "myrcene": 25},
        "aroma": "Hachís afgano, regaliz dulce y toques metálicos",
        "flavor": ["Hachís afgano", "Regaliz dulce", "Kush especiado", "Toque metálico"],
        "effects": ["Paz mental serena", "Relajación física no noqueante", "Alivio del dolor", "Sensación zen"],
        "difficulty": "Fácil",
        "description": "Unknown Kush (Desconocida Kush) es una de las variedades medicinales más afamadas de Delicious Seeds. Resultado de cruzar la galardonada Bay 11 con un clon secreto de linaje Kush. Proporciona una rica mezcla aromática de hachís afgano con notas de regaliz y un equilibrio mental-físico perfecto.",
        "gradient": "linear-gradient(135deg, #161c16 0%, #2f452d 50%, #10B981 100%)",
        "activities": ["Yoga y estiramientos", "Alivio de molestias", "Lectura reflexiva", "Relajación vespertina"]
    },

    # --- MR. NICE SEEDBANK ---
    {
        "id": "super-silver-haze-mrnice",
        "image": "images/strains/super-silver-haze-mrnice.jpg",
        "name": "Super Silver Haze",
        "aka": "SSH Shantibaba Original",
        "bank": "Mr. Nice Seedbank",
        "species": "Sativa",
        "indicaPct": 25,
        "sativaPct": 75,
        "thc": 21,
        "cbd": 0.3,
        "yieldIndoor": 550,
        "yieldOutdoor": 650,
        "floweringDays": 70,
        "rating": 4.9,
        "reviewsCount": 2150,
        "lineage": "Skunk #1 x Northern Lights #5 x Haze",
        "genetics": "(NL #5 x Haze C) x (Skunk #1 x Haze C)",
        "origin": "Ámsterdam / Suiza",
        "dominantTerpene": "terpinolene",
        "terpenes": {"terpinolene": 50, "myrcene": 30, "caryophyllene": 20},
        "aroma": "Incienso catedralicio, especias dulces y cítrico Haze",
        "flavor": ["Incienso puro", "Pino cítrico", "Pimienta suave", "Madera noble"],
        "effects": ["Euforia cerebral estratosférica", "Claridad mental nítida", "Creatividad infinita", "Energía"],
        "difficulty": "Media-alta",
        "description": "La auténtica Super Silver Haze original criada por Shantibaba y Neville Schoenmakers para Mr. Nice Seedbank, triple campeona consecutiva de la High Times Cannabis Cup (1997, 1998, 1999). Híbrida sativa cumbre que combina el poder de Skunk #1, Northern Lights #5 y Haze en una sinfonía de resina plateada e incienso sagrado.",
        "gradient": "linear-gradient(135deg, #1f241a 0%, #44542d 50%, #10B981 100%)",
        "activities": ["Creación artística", "Debates profundos", "Exploración", "Socializar en fiestas"]
    },
    {
        "id": "black-widow",
        "image": "images/strains/black-widow.jpg",
        "name": "Black Widow",
        "aka": "The Original White Widow 1994",
        "bank": "Mr. Nice Seedbank",
        "species": "Híbrida",
        "indicaPct": 60,
        "sativaPct": 40,
        "thc": 20,
        "cbd": 0.4,
        "yieldIndoor": 450,
        "yieldOutdoor": 600,
        "floweringDays": 60,
        "rating": 4.9,
        "reviewsCount": 1950,
        "lineage": "Landrace Brasil x Landrace Sur de la India (White Widow Original 1994)",
        "genetics": "Brazilian Sativa x South Indian Indica IBL",
        "origin": "Ámsterdam / Países Bajos (1994)",
        "dominantTerpene": "myrcene",
        "terpenes": {"myrcene": 50, "caryophyllene": 30, "pinene": 20},
        "aroma": "Pino fresco, especias amaderadas y resina agridulce",
        "flavor": ["Pino silvestre", "Especias amaderadas", "Terroso agridulce", "Hachís limpio"],
        "effects": ["Golpe cerebral potente", "Relajación física envolvente", "Efecto narcótico balanceado", "Paz"],
        "difficulty": "Fácil",
        "description": "Black Widow es el linaje original y genuino de la legendaria White Widow creada en 1994 por Shantibaba, preservada bajo este nombre en Mr. Nice Seedbank tras su salida de Green House. Mantiene la pureza genética de la madre sativa brasileña y el padre índica del sur de la India con su inigualable manto de tricomas cristalinos.",
        "gradient": "linear-gradient(135deg, #141716 0%, #2f3836 50%, #10B981 100%)",
        "activities": ["Sesión de descanso", "Música clásica o ambient", "Desconexión", "Calma tras el trabajo"]
    },
    {
        "id": "critical-mass-mrnice",
        "image": "images/strains/critical-mass-mrnice.jpg",
        "name": "Critical Mass",
        "aka": "Big Bud Revamped by Shantibaba",
        "bank": "Mr. Nice Seedbank",
        "species": "Índica",
        "indicaPct": 80,
        "sativaPct": 20,
        "thc": 20,
        "cbd": 0.4,
        "yieldIndoor": 650,
        "yieldOutdoor": 800,
        "floweringDays": 50,
        "rating": 4.9,
        "reviewsCount": 2300,
        "lineage": "Afghani x Skunk #1",
        "genetics": "Afghani Indica x Skunk #1 Elite Selection",
        "origin": "Países Bajos / Suiza",
        "dominantTerpene": "myrcene",
        "terpenes": {"myrcene": 55, "caryophyllene": 25, "limonene": 20},
        "aroma": "Skunk dulce, fruta madura y fondo almizclado",
        "flavor": ["Skunk dulce", "Fruta madura", "Almizcle", "Cítrico suave"],
        "effects": ["Relajación muscular total", "Efecto couchlock dulce", "Alivio del insomnio", "Serenidad"],
        "difficulty": "Muy fácil",
        "description": "Critical Mass es la legendaria evolución de Big Bud perfeccionada por Shantibaba. Famosa por sus racimos florales gigantescos y tan pesados que a menudo parten las ramas si no se tutorizan. Floración relámpago de solo 50 días y un efecto índico reconfortante cargado de notas afrutadas a Skunk.",
        "gradient": "linear-gradient(135deg, #182216 0%, #35522e 50%, #10B981 100%)",
        "activities": ["Dormir plácidamente", "Relajar la musculatura", "Ver películas", "Desconectar la mente"]
    },
    {
        "id": "medicine-man",
        "image": "images/strains/medicine-man.jpg",
        "name": "Medicine Man",
        "aka": "White Rhino Original",
        "bank": "Mr. Nice Seedbank",
        "species": "Índica",
        "indicaPct": 85,
        "sativaPct": 15,
        "thc": 20,
        "cbd": 0.5,
        "yieldIndoor": 500,
        "yieldOutdoor": 600,
        "floweringDays": 58,
        "rating": 4.8,
        "reviewsCount": 1420,
        "lineage": "White Widow x Afghani (White Rhino Original)",
        "genetics": "Brazilian/South Indian Hybrid x Afghani",
        "origin": "Suiza / Países Bajos",
        "dominantTerpene": "caryophyllene",
        "terpenes": {"caryophyllene": 45, "myrcene": 35, "humulene": 20},
        "aroma": "Hachís terroso, bosque húmedo y fondo Skunk dulce",
        "flavor": ["Hachís terroso", "Madera húmeda", "Skunk dulce", "Pino noble"],
        "effects": ["Sedación médica intensa", "Alivio de dolores crónicos", "Calma corporal profunda", "Somnolencia"],
        "difficulty": "Fácil",
        "description": "Medicine Man es el nombre original de White Rhino en Mr. Nice Seedbank. Fusión de White Widow con una vigorosa índica afgana que eleva la producción de resina y cannabinoides medicinales al máximo. Reconocida por su contundencia narcótica para tratar dolores severos e insomnio.",
        "gradient": "linear-gradient(135deg, #19141f 0%, #382b47 50%, #10B981 100%)",
        "activities": ["Uso terapéutico", "Descanso profundo", "Alivio de inflamaciones", "Sueño reparador"]
    },
    {
        "id": "nevilles-haze-mrnice",
        "image": "images/strains/nevilles-haze-mrnice.jpg",
        "name": "Neville's Haze",
        "aka": "The Holy Grail of Pure Hazes",
        "bank": "Mr. Nice Seedbank",
        "species": "Sativa",
        "indicaPct": 10,
        "sativaPct": 90,
        "thc": 22,
        "cbd": 0.2,
        "yieldIndoor": 550,
        "yieldOutdoor": 700,
        "floweringDays": 95,
        "rating": 4.9,
        "reviewsCount": 1650,
        "lineage": "Original Haze x Northern Lights #5",
        "genetics": "Pure Haze x Northern Lights #5A",
        "origin": "Países Bajos (Neville Schoenmakers)",
        "dominantTerpene": "pinene",
        "terpenes": {"pinene": 45, "terpinolene": 35, "caryophyllene": 20},
        "aroma": "Cedro puro, incienso aromático y notas a cuero",
        "flavor": ["Cedro aromático", "Incienso puro", "Cuero noble", "Cítrico añejo"],
        "effects": ["Viaje cerebral psicodélico", "Claridad cósmica", "Inspiración sublime", "Estimulación viva"],
        "difficulty": "Avanzada",
        "description": "Neville's Haze es el tributo eterno al padre de la crianza moderna, Neville Schoenmakers. Con casi 14 semanas de floración, es el santo grial de las Haze puras para conocedores expertos. Produce un efecto cerebral electrizante y expansivo con un aroma puro a madera noble de cedro e incienso.",
        "gradient": "linear-gradient(135deg, #1f2113 0%, #464a22 50%, #10B981 100%)",
        "activities": ["Filosofía y reflexión", "Composición artística", "Proyectos intelectuales", "Música envolvente"]
    },
    {
        "id": "early-skunk-mrnice",
        "image": "images/strains/early-skunk-mrnice.jpg",
        "name": "Early Skunk",
        "aka": "Outdoor Guerilla Master",
        "bank": "Mr. Nice Seedbank",
        "species": "Híbrida",
        "indicaPct": 50,
        "sativaPct": 50,
        "thc": 18,
        "cbd": 0.3,
        "yieldIndoor": 500,
        "yieldOutdoor": 650,
        "floweringDays": 50,
        "rating": 4.7,
        "reviewsCount": 1120,
        "lineage": "Early Pearl x Skunk #1",
        "genetics": "Early Pearl x Skunk #1",
        "origin": "Suiza / Países Bajos",
        "dominantTerpene": "myrcene",
        "terpenes": {"myrcene": 45, "pinene": 30, "caryophyllene": 25},
        "aroma": "Skunk punzante, fruta dulce y especias",
        "flavor": ["Skunk clásico", "Fruta dulce", "Especias terrosas", "Pino fresco"],
        "effects": ["Subidón alegre y social", "Relajación física confortable", "Equilibrio cuerpo-mente", "Bienestar"],
        "difficulty": "Muy fácil",
        "description": "Early Skunk de Mr. Nice Seedbank combina la resistencia al frío y la floración temprana de Early Pearl con la potencia y sabor inconfundibles de Skunk #1. La opción por excelencia para cultivadores de exterior en climas difíciles y cosechas rápidas y seguras.",
        "gradient": "linear-gradient(135deg, #152218 0%, #2f4d34 50%, #10B981 100%)",
        "activities": ["Día de campo", "Actividades sociales", "Barbacoas", "Caminar al atardecer"]
    },
    {
        "id": "shark-shock",
        "image": "images/strains/shark-shock.jpg",
        "name": "Shark Shock",
        "aka": "Great White Shark Original / Peacemaker",
        "bank": "Mr. Nice Seedbank",
        "species": "Índica",
        "indicaPct": 80,
        "sativaPct": 20,
        "thc": 19,
        "cbd": 0.4,
        "yieldIndoor": 550,
        "yieldOutdoor": 600,
        "floweringDays": 55,
        "rating": 4.8,
        "reviewsCount": 1310,
        "lineage": "Skunk #1 x White Widow (Great White Shark Original)",
        "genetics": "Skunk #1 x Black Widow (White Widow)",
        "origin": "Países Bajos / Suiza",
        "dominantTerpene": "caryophyllene",
        "terpenes": {"caryophyllene": 45, "myrcene": 35, "humulene": 20},
        "aroma": "Afrutado denso, cebolla dulce y resina espesa",
        "flavor": ["Fruta densa", "Cebolla dulce", "Resina espesa", "Toque floral Skunk"],
        "effects": ["Paz corporal profunda", "Sedación tranquila", "Desconexión de preocupaciones", "Alivio del dolor"],
        "difficulty": "Fácil",
        "description": "Shark Shock es el nombre original bajo el cual Shantibaba preservó Great White Shark (ganadora de la High Times Cannabis Cup 1997). Cruce demoledor de Skunk #1 con White Widow que produce flores en forma de torpedo cubiertas de resina con notas frutales y almizcle dulce.",
        "gradient": "linear-gradient(135deg, #181921 0%, #31354d 50%, #10B981 100%)",
        "activities": ["Desconexión total", "Alivio de tensiones musculares", "Descanso vespertino", "Dormir bien"]
    },
    {
        "id": "mango-haze",
        "image": "images/strains/mango-haze.jpg",
        "name": "Mango Haze",
        "aka": "Tropical Haze Sister",
        "bank": "Mr. Nice Seedbank",
        "species": "Sativa",
        "indicaPct": 25,
        "sativaPct": 75,
        "thc": 21,
        "cbd": 0.2,
        "yieldIndoor": 500,
        "yieldOutdoor": 600,
        "floweringDays": 68,
        "rating": 4.9,
        "reviewsCount": 1780,
        "lineage": "Northern Lights #5 x Skunk #1 x Haze",
        "genetics": "(NL #5 x Haze C) x (Skunk #1 x Haze C - Mango Pheno)",
        "origin": "Suiza / Países Bajos",
        "dominantTerpene": "myrcene",
        "terpenes": {"myrcene": 50, "limonene": 30, "terpinolene": 20},
        "aroma": "Mango maduro, fruta tropical ácida e incienso suave",
        "flavor": ["Mango maduro jugoso", "Fruta tropical", "Incienso suave", "Toque cítrico"],
        "effects": ["Euforia radiante y cálida", "Inspiración y creatividad", "Felicidad expansiva", "Claridad"],
        "difficulty": "Media",
        "description": "Mango Haze es la hermana dulce y tropical de Super Silver Haze, seleccionada por Shantibaba por su aroma embriagador a mangos maduros recién cortados con fondo inciensado Haze. Ofrece una de las experiencias organolépticas más deliciosas del mundo cannábico con un colocón eufórico y motivador.",
        "gradient": "linear-gradient(135deg, #241a10 0%, #59391b 50%, #10B981 100%)",
        "activities": ["Días creativos", "Música y baile", "Cocina gourmet", "Socializar en la naturaleza"]
    }
]

with open('js/data.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Verify no duplicate IDs
existing_ids = set(re.findall(r'id:\s*["\']([^"\']+)["\']', content))
duplicates = [s['id'] for s in new_strains if s['id'] in existing_ids]
if duplicates:
    print(f"❌ Error: IDs duplicados encontrados: {duplicates}")
    sys.exit(1)

# Find the end of STRAINS_DATABASE array
end_bracket = content.rfind('];')
if end_bracket == -1:
    end_bracket = content.rfind(']')

if end_bracket == -1:
    print("❌ Error: No se encontró el cierre de STRAINS_DATABASE en js/data.js")
    sys.exit(1)

# Format each strain as clean JavaScript object
import json

def format_js_obj(s):
    lines = ["  {"]
    for k, v in s.items():
        if isinstance(v, str):
            # escape double quotes if needed
            v_esc = v.replace('"', '\\"')
            lines.append(f'    {k}: "{v_esc}",')
        elif isinstance(v, (int, float)):
            lines.append(f'    {k}: {v},')
        elif isinstance(v, list):
            items = ", ".join([f'"{x}"' for x in v])
            lines.append(f'    {k}: [{items}],')
        elif isinstance(v, dict):
            dict_str = ", ".join([f"{dk}: {dv}" for dk, dv in v.items()])
            lines.append(f'    {k}: {{ {dict_str} }},')
    lines.append("  }")
    return "\n".join(lines)

js_strains = ",\n" + ",\n".join([format_js_obj(s) for s in new_strains])

# Insert before end_bracket
new_content = content[:end_bracket].rstrip() + js_strains + "\n" + content[end_bracket:]

with open('js/data.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"✅ Inserción exitosa de {len(new_strains)} cepas (8 Delicious Seeds + 8 Mr. Nice Seedbank) en js/data.js")
